//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.04 at 01:40:50 PM MEZ 
//


package eu.europa.publications.formex.ted.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for annex_d1 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="annex_d1">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;group ref="{http://formex.publications.europa.eu/ted/schema/reception/R2.0.9.S01}annex_d1_part1"/>
 *           &lt;group ref="{http://formex.publications.europa.eu/ted/schema/reception/R2.0.9.S01}annex_part2"/>
 *         &lt;/choice>
 *         &lt;element ref="{http://formex.publications.europa.eu/ted/schema/reception/R2.0.9.S01}D_JUSTIFICATION"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "annex_d1", propOrder = {
    "doutsidescope",
    "daccordancearticle",
    "djustification"
})
public class AnnexD1
    implements Equals, HashCode, ToString
{

    @XmlElement(name = "D_OUTSIDE_SCOPE")
    protected Empty doutsidescope;
    @XmlElement(name = "D_ACCORDANCE_ARTICLE")
    protected eu.europa.publications.formex.ted.schema.ProcedureF15 .DIRECTIVE201424EU.PTNEGOTIATEDWITHOUTPUBLICATION.DACCORDANCEARTICLE daccordancearticle;
    @XmlElement(name = "D_JUSTIFICATION", required = true)
    protected TextFtMultiLines djustification;

    /**
     * Other justification for the award of the award of the contract without prior publication
     * 
     * @return
     *     possible object is
     *     {@link Empty }
     *     
     */
    public Empty getDOUTSIDESCOPE() {
        return doutsidescope;
    }

    /**
     * Sets the value of the doutsidescope property.
     * 
     * @param value
     *     allowed object is
     *     {@link Empty }
     *     
     */
    public void setDOUTSIDESCOPE(Empty value) {
        this.doutsidescope = value;
    }

    /**
     * Gets the value of the daccordancearticle property.
     * 
     * @return
     *     possible object is
     *     {@link eu.europa.publications.formex.ted.schema.ProcedureF15 .DIRECTIVE201424EU.PTNEGOTIATEDWITHOUTPUBLICATION.DACCORDANCEARTICLE }
     *     
     */
    public eu.europa.publications.formex.ted.schema.ProcedureF15 .DIRECTIVE201424EU.PTNEGOTIATEDWITHOUTPUBLICATION.DACCORDANCEARTICLE getDACCORDANCEARTICLE() {
        return daccordancearticle;
    }

    /**
     * Sets the value of the daccordancearticle property.
     * 
     * @param value
     *     allowed object is
     *     {@link eu.europa.publications.formex.ted.schema.ProcedureF15 .DIRECTIVE201424EU.PTNEGOTIATEDWITHOUTPUBLICATION.DACCORDANCEARTICLE }
     *     
     */
    public void setDACCORDANCEARTICLE(eu.europa.publications.formex.ted.schema.ProcedureF15 .DIRECTIVE201424EU.PTNEGOTIATEDWITHOUTPUBLICATION.DACCORDANCEARTICLE value) {
        this.daccordancearticle = value;
    }

    /**
     * Gets the value of the djustification property.
     * 
     * @return
     *     possible object is
     *     {@link TextFtMultiLines }
     *     
     */
    public TextFtMultiLines getDJUSTIFICATION() {
        return djustification;
    }

    /**
     * Sets the value of the djustification property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextFtMultiLines }
     *     
     */
    public void setDJUSTIFICATION(TextFtMultiLines value) {
        this.djustification = value;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof AnnexD1)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final AnnexD1 that = ((AnnexD1) object);
        {
            Empty lhsDOUTSIDESCOPE;
            lhsDOUTSIDESCOPE = this.getDOUTSIDESCOPE();
            Empty rhsDOUTSIDESCOPE;
            rhsDOUTSIDESCOPE = that.getDOUTSIDESCOPE();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "doutsidescope", lhsDOUTSIDESCOPE), LocatorUtils.property(thatLocator, "doutsidescope", rhsDOUTSIDESCOPE), lhsDOUTSIDESCOPE, rhsDOUTSIDESCOPE)) {
                return false;
            }
        }
        {
            eu.europa.publications.formex.ted.schema.ProcedureF15 .DIRECTIVE201424EU.PTNEGOTIATEDWITHOUTPUBLICATION.DACCORDANCEARTICLE lhsDACCORDANCEARTICLE;
            lhsDACCORDANCEARTICLE = this.getDACCORDANCEARTICLE();
            eu.europa.publications.formex.ted.schema.ProcedureF15 .DIRECTIVE201424EU.PTNEGOTIATEDWITHOUTPUBLICATION.DACCORDANCEARTICLE rhsDACCORDANCEARTICLE;
            rhsDACCORDANCEARTICLE = that.getDACCORDANCEARTICLE();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "daccordancearticle", lhsDACCORDANCEARTICLE), LocatorUtils.property(thatLocator, "daccordancearticle", rhsDACCORDANCEARTICLE), lhsDACCORDANCEARTICLE, rhsDACCORDANCEARTICLE)) {
                return false;
            }
        }
        {
            TextFtMultiLines lhsDJUSTIFICATION;
            lhsDJUSTIFICATION = this.getDJUSTIFICATION();
            TextFtMultiLines rhsDJUSTIFICATION;
            rhsDJUSTIFICATION = that.getDJUSTIFICATION();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "djustification", lhsDJUSTIFICATION), LocatorUtils.property(thatLocator, "djustification", rhsDJUSTIFICATION), lhsDJUSTIFICATION, rhsDJUSTIFICATION)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = 1;
        {
            Empty theDOUTSIDESCOPE;
            theDOUTSIDESCOPE = this.getDOUTSIDESCOPE();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "doutsidescope", theDOUTSIDESCOPE), currentHashCode, theDOUTSIDESCOPE);
        }
        {
            eu.europa.publications.formex.ted.schema.ProcedureF15 .DIRECTIVE201424EU.PTNEGOTIATEDWITHOUTPUBLICATION.DACCORDANCEARTICLE theDACCORDANCEARTICLE;
            theDACCORDANCEARTICLE = this.getDACCORDANCEARTICLE();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "daccordancearticle", theDACCORDANCEARTICLE), currentHashCode, theDACCORDANCEARTICLE);
        }
        {
            TextFtMultiLines theDJUSTIFICATION;
            theDJUSTIFICATION = this.getDJUSTIFICATION();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "djustification", theDJUSTIFICATION), currentHashCode, theDJUSTIFICATION);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        {
            Empty theDOUTSIDESCOPE;
            theDOUTSIDESCOPE = this.getDOUTSIDESCOPE();
            strategy.appendField(locator, this, "doutsidescope", buffer, theDOUTSIDESCOPE);
        }
        {
            eu.europa.publications.formex.ted.schema.ProcedureF15 .DIRECTIVE201424EU.PTNEGOTIATEDWITHOUTPUBLICATION.DACCORDANCEARTICLE theDACCORDANCEARTICLE;
            theDACCORDANCEARTICLE = this.getDACCORDANCEARTICLE();
            strategy.appendField(locator, this, "daccordancearticle", buffer, theDACCORDANCEARTICLE);
        }
        {
            TextFtMultiLines theDJUSTIFICATION;
            theDJUSTIFICATION = this.getDJUSTIFICATION();
            strategy.appendField(locator, this, "djustification", buffer, theDJUSTIFICATION);
        }
        return buffer;
    }

}
