//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.04 at 01:40:50 PM MEZ 
//


package eu.europa.publications.formex.ted.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * Section V: AWARD OF CONTRACT / CONCESSION
 * 
 * <p>Java class for award_contract_f20 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="award_contract_f20">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://formex.publications.europa.eu/ted/schema/reception/R2.0.9.S01}CONTRACT_NO"/>
 *         &lt;element ref="{http://formex.publications.europa.eu/ted/schema/reception/R2.0.9.S01}LOT_NO" minOccurs="0"/>
 *         &lt;element ref="{http://formex.publications.europa.eu/ted/schema/reception/R2.0.9.S01}TITLE"/>
 *         &lt;element name="AWARDED_CONTRACT">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://formex.publications.europa.eu/ted/schema/reception/R2.0.9.S01}DATE_CONCLUSION_CONTRACT"/>
 *                   &lt;group ref="{http://formex.publications.europa.eu/ted/schema/reception/R2.0.9.S01}contractor"/>
 *                   &lt;element ref="{http://formex.publications.europa.eu/ted/schema/reception/R2.0.9.S01}VAL_TOTAL"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "award_contract_f20", propOrder = {
    "contractno",
    "lotno",
    "title",
    "awardedcontract"
})
public class AwardContractF20
    implements Equals, HashCode, ToString
{

    @XmlElement(name = "CONTRACT_NO", required = true)
    protected String contractno;
    @XmlElement(name = "LOT_NO")
    protected String lotno;
    @XmlElement(name = "TITLE", required = true)
    protected TITLE title;
    @XmlElement(name = "AWARDED_CONTRACT", required = true)
    protected AwardContractF20 .AWARDEDCONTRACT awardedcontract;

    /**
     * Gets the value of the contractno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCONTRACTNO() {
        return contractno;
    }

    /**
     * Sets the value of the contractno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCONTRACTNO(String value) {
        this.contractno = value;
    }

    /**
     * Gets the value of the lotno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLOTNO() {
        return lotno;
    }

    /**
     * Sets the value of the lotno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLOTNO(String value) {
        this.lotno = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link TITLE }
     *     
     */
    public TITLE getTITLE() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link TITLE }
     *     
     */
    public void setTITLE(TITLE value) {
        this.title = value;
    }

    /**
     * Gets the value of the awardedcontract property.
     * 
     * @return
     *     possible object is
     *     {@link AwardContractF20 .AWARDEDCONTRACT }
     *     
     */
    public AwardContractF20 .AWARDEDCONTRACT getAWARDEDCONTRACT() {
        return awardedcontract;
    }

    /**
     * Sets the value of the awardedcontract property.
     * 
     * @param value
     *     allowed object is
     *     {@link AwardContractF20 .AWARDEDCONTRACT }
     *     
     */
    public void setAWARDEDCONTRACT(AwardContractF20 .AWARDEDCONTRACT value) {
        this.awardedcontract = value;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof AwardContractF20)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final AwardContractF20 that = ((AwardContractF20) object);
        {
            String lhsCONTRACTNO;
            lhsCONTRACTNO = this.getCONTRACTNO();
            String rhsCONTRACTNO;
            rhsCONTRACTNO = that.getCONTRACTNO();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "contractno", lhsCONTRACTNO), LocatorUtils.property(thatLocator, "contractno", rhsCONTRACTNO), lhsCONTRACTNO, rhsCONTRACTNO)) {
                return false;
            }
        }
        {
            String lhsLOTNO;
            lhsLOTNO = this.getLOTNO();
            String rhsLOTNO;
            rhsLOTNO = that.getLOTNO();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "lotno", lhsLOTNO), LocatorUtils.property(thatLocator, "lotno", rhsLOTNO), lhsLOTNO, rhsLOTNO)) {
                return false;
            }
        }
        {
            TITLE lhsTITLE;
            lhsTITLE = this.getTITLE();
            TITLE rhsTITLE;
            rhsTITLE = that.getTITLE();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "title", lhsTITLE), LocatorUtils.property(thatLocator, "title", rhsTITLE), lhsTITLE, rhsTITLE)) {
                return false;
            }
        }
        {
            AwardContractF20 .AWARDEDCONTRACT lhsAWARDEDCONTRACT;
            lhsAWARDEDCONTRACT = this.getAWARDEDCONTRACT();
            AwardContractF20 .AWARDEDCONTRACT rhsAWARDEDCONTRACT;
            rhsAWARDEDCONTRACT = that.getAWARDEDCONTRACT();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "awardedcontract", lhsAWARDEDCONTRACT), LocatorUtils.property(thatLocator, "awardedcontract", rhsAWARDEDCONTRACT), lhsAWARDEDCONTRACT, rhsAWARDEDCONTRACT)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = 1;
        {
            String theCONTRACTNO;
            theCONTRACTNO = this.getCONTRACTNO();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "contractno", theCONTRACTNO), currentHashCode, theCONTRACTNO);
        }
        {
            String theLOTNO;
            theLOTNO = this.getLOTNO();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "lotno", theLOTNO), currentHashCode, theLOTNO);
        }
        {
            TITLE theTITLE;
            theTITLE = this.getTITLE();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "title", theTITLE), currentHashCode, theTITLE);
        }
        {
            AwardContractF20 .AWARDEDCONTRACT theAWARDEDCONTRACT;
            theAWARDEDCONTRACT = this.getAWARDEDCONTRACT();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "awardedcontract", theAWARDEDCONTRACT), currentHashCode, theAWARDEDCONTRACT);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        {
            String theCONTRACTNO;
            theCONTRACTNO = this.getCONTRACTNO();
            strategy.appendField(locator, this, "contractno", buffer, theCONTRACTNO);
        }
        {
            String theLOTNO;
            theLOTNO = this.getLOTNO();
            strategy.appendField(locator, this, "lotno", buffer, theLOTNO);
        }
        {
            TITLE theTITLE;
            theTITLE = this.getTITLE();
            strategy.appendField(locator, this, "title", buffer, theTITLE);
        }
        {
            AwardContractF20 .AWARDEDCONTRACT theAWARDEDCONTRACT;
            theAWARDEDCONTRACT = this.getAWARDEDCONTRACT();
            strategy.appendField(locator, this, "awardedcontract", buffer, theAWARDEDCONTRACT);
        }
        return buffer;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://formex.publications.europa.eu/ted/schema/reception/R2.0.9.S01}DATE_CONCLUSION_CONTRACT"/>
     *         &lt;group ref="{http://formex.publications.europa.eu/ted/schema/reception/R2.0.9.S01}contractor"/>
     *         &lt;element ref="{http://formex.publications.europa.eu/ted/schema/reception/R2.0.9.S01}VAL_TOTAL"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "dateconclusioncontract",
        "noawardedtogroup",
        "awardedtogroup",
        "contractors",
        "valtotal"
    })
    public static class AWARDEDCONTRACT
        implements Equals, HashCode, ToString
    {

        @XmlElement(name = "DATE_CONCLUSION_CONTRACT", required = true)
        protected XMLGregorianCalendar dateconclusioncontract;
        @XmlElement(name = "NO_AWARDED_TO_GROUP")
        protected Empty noawardedtogroup;
        @XmlElement(name = "AWARDED_TO_GROUP")
        protected Empty awardedtogroup;
        @XmlElement(name = "CONTRACTOR")
        protected List<AwardContractF20 .AWARDEDCONTRACT.CONTRACTOR> contractors;
        @XmlElement(name = "VAL_TOTAL", required = true)
        protected Val valtotal;

        /**
         * Gets the value of the dateconclusioncontract property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDATECONCLUSIONCONTRACT() {
            return dateconclusioncontract;
        }

        /**
         * Sets the value of the dateconclusioncontract property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDATECONCLUSIONCONTRACT(XMLGregorianCalendar value) {
            this.dateconclusioncontract = value;
        }

        /**
         * Gets the value of the noawardedtogroup property.
         * 
         * @return
         *     possible object is
         *     {@link Empty }
         *     
         */
        public Empty getNOAWARDEDTOGROUP() {
            return noawardedtogroup;
        }

        /**
         * Sets the value of the noawardedtogroup property.
         * 
         * @param value
         *     allowed object is
         *     {@link Empty }
         *     
         */
        public void setNOAWARDEDTOGROUP(Empty value) {
            this.noawardedtogroup = value;
        }

        /**
         * Gets the value of the awardedtogroup property.
         * 
         * @return
         *     possible object is
         *     {@link Empty }
         *     
         */
        public Empty getAWARDEDTOGROUP() {
            return awardedtogroup;
        }

        /**
         * Sets the value of the awardedtogroup property.
         * 
         * @param value
         *     allowed object is
         *     {@link Empty }
         *     
         */
        public void setAWARDEDTOGROUP(Empty value) {
            this.awardedtogroup = value;
        }

        /**
         * Gets the value of the contractors property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the contractors property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCONTRACTORS().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link AwardContractF20 .AWARDEDCONTRACT.CONTRACTOR }
         * 
         * 
         */
        public List<AwardContractF20 .AWARDEDCONTRACT.CONTRACTOR> getCONTRACTORS() {
            if (contractors == null) {
                contractors = new ArrayList<AwardContractF20 .AWARDEDCONTRACT.CONTRACTOR>();
            }
            return this.contractors;
        }

        /**
         * Gets the value of the valtotal property.
         * 
         * @return
         *     possible object is
         *     {@link Val }
         *     
         */
        public Val getVALTOTAL() {
            return valtotal;
        }

        /**
         * Sets the value of the valtotal property.
         * 
         * @param value
         *     allowed object is
         *     {@link Val }
         *     
         */
        public void setVALTOTAL(Val value) {
            this.valtotal = value;
        }

        public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
            if (!(object instanceof AwardContractF20 .AWARDEDCONTRACT)) {
                return false;
            }
            if (this == object) {
                return true;
            }
            final AwardContractF20 .AWARDEDCONTRACT that = ((AwardContractF20 .AWARDEDCONTRACT) object);
            {
                XMLGregorianCalendar lhsDATECONCLUSIONCONTRACT;
                lhsDATECONCLUSIONCONTRACT = this.getDATECONCLUSIONCONTRACT();
                XMLGregorianCalendar rhsDATECONCLUSIONCONTRACT;
                rhsDATECONCLUSIONCONTRACT = that.getDATECONCLUSIONCONTRACT();
                if (!strategy.equals(LocatorUtils.property(thisLocator, "dateconclusioncontract", lhsDATECONCLUSIONCONTRACT), LocatorUtils.property(thatLocator, "dateconclusioncontract", rhsDATECONCLUSIONCONTRACT), lhsDATECONCLUSIONCONTRACT, rhsDATECONCLUSIONCONTRACT)) {
                    return false;
                }
            }
            {
                Empty lhsNOAWARDEDTOGROUP;
                lhsNOAWARDEDTOGROUP = this.getNOAWARDEDTOGROUP();
                Empty rhsNOAWARDEDTOGROUP;
                rhsNOAWARDEDTOGROUP = that.getNOAWARDEDTOGROUP();
                if (!strategy.equals(LocatorUtils.property(thisLocator, "noawardedtogroup", lhsNOAWARDEDTOGROUP), LocatorUtils.property(thatLocator, "noawardedtogroup", rhsNOAWARDEDTOGROUP), lhsNOAWARDEDTOGROUP, rhsNOAWARDEDTOGROUP)) {
                    return false;
                }
            }
            {
                Empty lhsAWARDEDTOGROUP;
                lhsAWARDEDTOGROUP = this.getAWARDEDTOGROUP();
                Empty rhsAWARDEDTOGROUP;
                rhsAWARDEDTOGROUP = that.getAWARDEDTOGROUP();
                if (!strategy.equals(LocatorUtils.property(thisLocator, "awardedtogroup", lhsAWARDEDTOGROUP), LocatorUtils.property(thatLocator, "awardedtogroup", rhsAWARDEDTOGROUP), lhsAWARDEDTOGROUP, rhsAWARDEDTOGROUP)) {
                    return false;
                }
            }
            {
                List<AwardContractF20 .AWARDEDCONTRACT.CONTRACTOR> lhsCONTRACTORS;
                lhsCONTRACTORS = (((this.contractors!= null)&&(!this.contractors.isEmpty()))?this.getCONTRACTORS():null);
                List<AwardContractF20 .AWARDEDCONTRACT.CONTRACTOR> rhsCONTRACTORS;
                rhsCONTRACTORS = (((that.contractors!= null)&&(!that.contractors.isEmpty()))?that.getCONTRACTORS():null);
                if (!strategy.equals(LocatorUtils.property(thisLocator, "contractors", lhsCONTRACTORS), LocatorUtils.property(thatLocator, "contractors", rhsCONTRACTORS), lhsCONTRACTORS, rhsCONTRACTORS)) {
                    return false;
                }
            }
            {
                Val lhsVALTOTAL;
                lhsVALTOTAL = this.getVALTOTAL();
                Val rhsVALTOTAL;
                rhsVALTOTAL = that.getVALTOTAL();
                if (!strategy.equals(LocatorUtils.property(thisLocator, "valtotal", lhsVALTOTAL), LocatorUtils.property(thatLocator, "valtotal", rhsVALTOTAL), lhsVALTOTAL, rhsVALTOTAL)) {
                    return false;
                }
            }
            return true;
        }

        public boolean equals(Object object) {
            final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
            return equals(null, null, object, strategy);
        }

        public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
            int currentHashCode = 1;
            {
                XMLGregorianCalendar theDATECONCLUSIONCONTRACT;
                theDATECONCLUSIONCONTRACT = this.getDATECONCLUSIONCONTRACT();
                currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "dateconclusioncontract", theDATECONCLUSIONCONTRACT), currentHashCode, theDATECONCLUSIONCONTRACT);
            }
            {
                Empty theNOAWARDEDTOGROUP;
                theNOAWARDEDTOGROUP = this.getNOAWARDEDTOGROUP();
                currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "noawardedtogroup", theNOAWARDEDTOGROUP), currentHashCode, theNOAWARDEDTOGROUP);
            }
            {
                Empty theAWARDEDTOGROUP;
                theAWARDEDTOGROUP = this.getAWARDEDTOGROUP();
                currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "awardedtogroup", theAWARDEDTOGROUP), currentHashCode, theAWARDEDTOGROUP);
            }
            {
                List<AwardContractF20 .AWARDEDCONTRACT.CONTRACTOR> theCONTRACTORS;
                theCONTRACTORS = (((this.contractors!= null)&&(!this.contractors.isEmpty()))?this.getCONTRACTORS():null);
                currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "contractors", theCONTRACTORS), currentHashCode, theCONTRACTORS);
            }
            {
                Val theVALTOTAL;
                theVALTOTAL = this.getVALTOTAL();
                currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "valtotal", theVALTOTAL), currentHashCode, theVALTOTAL);
            }
            return currentHashCode;
        }

        public int hashCode() {
            final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
            return this.hashCode(null, strategy);
        }

        public String toString() {
            final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
            final StringBuilder buffer = new StringBuilder();
            append(null, buffer, strategy);
            return buffer.toString();
        }

        public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
            strategy.appendStart(locator, this, buffer);
            appendFields(locator, buffer, strategy);
            strategy.appendEnd(locator, this, buffer);
            return buffer;
        }

        public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
            {
                XMLGregorianCalendar theDATECONCLUSIONCONTRACT;
                theDATECONCLUSIONCONTRACT = this.getDATECONCLUSIONCONTRACT();
                strategy.appendField(locator, this, "dateconclusioncontract", buffer, theDATECONCLUSIONCONTRACT);
            }
            {
                Empty theNOAWARDEDTOGROUP;
                theNOAWARDEDTOGROUP = this.getNOAWARDEDTOGROUP();
                strategy.appendField(locator, this, "noawardedtogroup", buffer, theNOAWARDEDTOGROUP);
            }
            {
                Empty theAWARDEDTOGROUP;
                theAWARDEDTOGROUP = this.getAWARDEDTOGROUP();
                strategy.appendField(locator, this, "awardedtogroup", buffer, theAWARDEDTOGROUP);
            }
            {
                List<AwardContractF20 .AWARDEDCONTRACT.CONTRACTOR> theCONTRACTORS;
                theCONTRACTORS = (((this.contractors!= null)&&(!this.contractors.isEmpty()))?this.getCONTRACTORS():null);
                strategy.appendField(locator, this, "contractors", buffer, theCONTRACTORS);
            }
            {
                Val theVALTOTAL;
                theVALTOTAL = this.getVALTOTAL();
                strategy.appendField(locator, this, "valtotal", buffer, theVALTOTAL);
            }
            return buffer;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element ref="{http://formex.publications.europa.eu/ted/schema/reception/R2.0.9.S01}ADDRESS_CONTRACTOR"/>
         *         &lt;choice>
         *           &lt;element ref="{http://formex.publications.europa.eu/ted/schema/reception/R2.0.9.S01}SME"/>
         *           &lt;element ref="{http://formex.publications.europa.eu/ted/schema/reception/R2.0.9.S01}NO_SME"/>
         *         &lt;/choice>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "addresscontractor",
            "nosme",
            "sme"
        })
        public static class CONTRACTOR
            implements Equals, HashCode, ToString
        {

            @XmlElement(name = "ADDRESS_CONTRACTOR", required = true)
            protected ContactContractor addresscontractor;
            @XmlElement(name = "NO_SME")
            protected Empty nosme;
            @XmlElement(name = "SME")
            protected Empty sme;

            /**
             * Gets the value of the addresscontractor property.
             * 
             * @return
             *     possible object is
             *     {@link ContactContractor }
             *     
             */
            public ContactContractor getADDRESSCONTRACTOR() {
                return addresscontractor;
            }

            /**
             * Sets the value of the addresscontractor property.
             * 
             * @param value
             *     allowed object is
             *     {@link ContactContractor }
             *     
             */
            public void setADDRESSCONTRACTOR(ContactContractor value) {
                this.addresscontractor = value;
            }

            /**
             * Gets the value of the nosme property.
             * 
             * @return
             *     possible object is
             *     {@link Empty }
             *     
             */
            public Empty getNOSME() {
                return nosme;
            }

            /**
             * Sets the value of the nosme property.
             * 
             * @param value
             *     allowed object is
             *     {@link Empty }
             *     
             */
            public void setNOSME(Empty value) {
                this.nosme = value;
            }

            /**
             * Gets the value of the sme property.
             * 
             * @return
             *     possible object is
             *     {@link Empty }
             *     
             */
            public Empty getSME() {
                return sme;
            }

            /**
             * Sets the value of the sme property.
             * 
             * @param value
             *     allowed object is
             *     {@link Empty }
             *     
             */
            public void setSME(Empty value) {
                this.sme = value;
            }

            public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
                if (!(object instanceof AwardContractF20 .AWARDEDCONTRACT.CONTRACTOR)) {
                    return false;
                }
                if (this == object) {
                    return true;
                }
                final AwardContractF20 .AWARDEDCONTRACT.CONTRACTOR that = ((AwardContractF20 .AWARDEDCONTRACT.CONTRACTOR) object);
                {
                    ContactContractor lhsADDRESSCONTRACTOR;
                    lhsADDRESSCONTRACTOR = this.getADDRESSCONTRACTOR();
                    ContactContractor rhsADDRESSCONTRACTOR;
                    rhsADDRESSCONTRACTOR = that.getADDRESSCONTRACTOR();
                    if (!strategy.equals(LocatorUtils.property(thisLocator, "addresscontractor", lhsADDRESSCONTRACTOR), LocatorUtils.property(thatLocator, "addresscontractor", rhsADDRESSCONTRACTOR), lhsADDRESSCONTRACTOR, rhsADDRESSCONTRACTOR)) {
                        return false;
                    }
                }
                {
                    Empty lhsNOSME;
                    lhsNOSME = this.getNOSME();
                    Empty rhsNOSME;
                    rhsNOSME = that.getNOSME();
                    if (!strategy.equals(LocatorUtils.property(thisLocator, "nosme", lhsNOSME), LocatorUtils.property(thatLocator, "nosme", rhsNOSME), lhsNOSME, rhsNOSME)) {
                        return false;
                    }
                }
                {
                    Empty lhsSME;
                    lhsSME = this.getSME();
                    Empty rhsSME;
                    rhsSME = that.getSME();
                    if (!strategy.equals(LocatorUtils.property(thisLocator, "sme", lhsSME), LocatorUtils.property(thatLocator, "sme", rhsSME), lhsSME, rhsSME)) {
                        return false;
                    }
                }
                return true;
            }

            public boolean equals(Object object) {
                final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
                return equals(null, null, object, strategy);
            }

            public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
                int currentHashCode = 1;
                {
                    ContactContractor theADDRESSCONTRACTOR;
                    theADDRESSCONTRACTOR = this.getADDRESSCONTRACTOR();
                    currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "addresscontractor", theADDRESSCONTRACTOR), currentHashCode, theADDRESSCONTRACTOR);
                }
                {
                    Empty theNOSME;
                    theNOSME = this.getNOSME();
                    currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "nosme", theNOSME), currentHashCode, theNOSME);
                }
                {
                    Empty theSME;
                    theSME = this.getSME();
                    currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "sme", theSME), currentHashCode, theSME);
                }
                return currentHashCode;
            }

            public int hashCode() {
                final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
                return this.hashCode(null, strategy);
            }

            public String toString() {
                final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
                final StringBuilder buffer = new StringBuilder();
                append(null, buffer, strategy);
                return buffer.toString();
            }

            public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
                strategy.appendStart(locator, this, buffer);
                appendFields(locator, buffer, strategy);
                strategy.appendEnd(locator, this, buffer);
                return buffer;
            }

            public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
                {
                    ContactContractor theADDRESSCONTRACTOR;
                    theADDRESSCONTRACTOR = this.getADDRESSCONTRACTOR();
                    strategy.appendField(locator, this, "addresscontractor", buffer, theADDRESSCONTRACTOR);
                }
                {
                    Empty theNOSME;
                    theNOSME = this.getNOSME();
                    strategy.appendField(locator, this, "nosme", buffer, theNOSME);
                }
                {
                    Empty theSME;
                    theSME = this.getSME();
                    strategy.appendField(locator, this, "sme", buffer, theSME);
                }
                return buffer;
            }

        }

    }

}
