//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.04 at 01:40:50 PM MEZ 
//


package eu.europa.publications.formex.ted.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for cpv_supplementary_codes complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="cpv_supplementary_codes">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="CODE" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="AA01"/>
 *             &lt;enumeration value="AA02"/>
 *             &lt;enumeration value="AA03"/>
 *             &lt;enumeration value="AA04"/>
 *             &lt;enumeration value="AA05"/>
 *             &lt;enumeration value="AA06"/>
 *             &lt;enumeration value="AA07"/>
 *             &lt;enumeration value="AA08"/>
 *             &lt;enumeration value="AA09"/>
 *             &lt;enumeration value="AA10"/>
 *             &lt;enumeration value="AA11"/>
 *             &lt;enumeration value="AA12"/>
 *             &lt;enumeration value="AA13"/>
 *             &lt;enumeration value="AA14"/>
 *             &lt;enumeration value="AA15"/>
 *             &lt;enumeration value="AA16"/>
 *             &lt;enumeration value="AA17"/>
 *             &lt;enumeration value="AA18"/>
 *             &lt;enumeration value="AA19"/>
 *             &lt;enumeration value="AA20"/>
 *             &lt;enumeration value="AA21"/>
 *             &lt;enumeration value="AA22"/>
 *             &lt;enumeration value="AA23"/>
 *             &lt;enumeration value="AA24"/>
 *             &lt;enumeration value="AA25"/>
 *             &lt;enumeration value="AA26"/>
 *             &lt;enumeration value="AA27"/>
 *             &lt;enumeration value="AA28"/>
 *             &lt;enumeration value="AA29"/>
 *             &lt;enumeration value="AA30"/>
 *             &lt;enumeration value="AA31"/>
 *             &lt;enumeration value="AA32"/>
 *             &lt;enumeration value="AA33"/>
 *             &lt;enumeration value="AA34"/>
 *             &lt;enumeration value="AA35"/>
 *             &lt;enumeration value="AA36"/>
 *             &lt;enumeration value="AA37"/>
 *             &lt;enumeration value="AA38"/>
 *             &lt;enumeration value="AA39"/>
 *             &lt;enumeration value="AA40"/>
 *             &lt;enumeration value="AA41"/>
 *             &lt;enumeration value="AA42"/>
 *             &lt;enumeration value="AA43"/>
 *             &lt;enumeration value="AA44"/>
 *             &lt;enumeration value="AA45"/>
 *             &lt;enumeration value="AA46"/>
 *             &lt;enumeration value="AA47"/>
 *             &lt;enumeration value="AA48"/>
 *             &lt;enumeration value="AB02"/>
 *             &lt;enumeration value="AB03"/>
 *             &lt;enumeration value="AB04"/>
 *             &lt;enumeration value="AB05"/>
 *             &lt;enumeration value="AB06"/>
 *             &lt;enumeration value="AB07"/>
 *             &lt;enumeration value="AB08"/>
 *             &lt;enumeration value="AB09"/>
 *             &lt;enumeration value="AB11"/>
 *             &lt;enumeration value="AB12"/>
 *             &lt;enumeration value="AB13"/>
 *             &lt;enumeration value="AB14"/>
 *             &lt;enumeration value="AB15"/>
 *             &lt;enumeration value="AB16"/>
 *             &lt;enumeration value="AB17"/>
 *             &lt;enumeration value="AB18"/>
 *             &lt;enumeration value="AB19"/>
 *             &lt;enumeration value="AB20"/>
 *             &lt;enumeration value="AB21"/>
 *             &lt;enumeration value="AB22"/>
 *             &lt;enumeration value="AB23"/>
 *             &lt;enumeration value="AB24"/>
 *             &lt;enumeration value="AB25"/>
 *             &lt;enumeration value="AB26"/>
 *             &lt;enumeration value="AB27"/>
 *             &lt;enumeration value="AB28"/>
 *             &lt;enumeration value="AB29"/>
 *             &lt;enumeration value="AB30"/>
 *             &lt;enumeration value="AB31"/>
 *             &lt;enumeration value="AB32"/>
 *             &lt;enumeration value="AB33"/>
 *             &lt;enumeration value="AB34"/>
 *             &lt;enumeration value="AB35"/>
 *             &lt;enumeration value="AB36"/>
 *             &lt;enumeration value="AB37"/>
 *             &lt;enumeration value="BA01"/>
 *             &lt;enumeration value="BA02"/>
 *             &lt;enumeration value="BA03"/>
 *             &lt;enumeration value="BA04"/>
 *             &lt;enumeration value="BA05"/>
 *             &lt;enumeration value="BA06"/>
 *             &lt;enumeration value="BA07"/>
 *             &lt;enumeration value="BA08"/>
 *             &lt;enumeration value="BA09"/>
 *             &lt;enumeration value="BA10"/>
 *             &lt;enumeration value="BA11"/>
 *             &lt;enumeration value="BA12"/>
 *             &lt;enumeration value="BA13"/>
 *             &lt;enumeration value="BA14"/>
 *             &lt;enumeration value="BA15"/>
 *             &lt;enumeration value="BA16"/>
 *             &lt;enumeration value="BA17"/>
 *             &lt;enumeration value="BA18"/>
 *             &lt;enumeration value="BA19"/>
 *             &lt;enumeration value="BA20"/>
 *             &lt;enumeration value="BA22"/>
 *             &lt;enumeration value="BA23"/>
 *             &lt;enumeration value="BA24"/>
 *             &lt;enumeration value="BA25"/>
 *             &lt;enumeration value="BA26"/>
 *             &lt;enumeration value="BA27"/>
 *             &lt;enumeration value="BA28"/>
 *             &lt;enumeration value="BA29"/>
 *             &lt;enumeration value="BA30"/>
 *             &lt;enumeration value="BA31"/>
 *             &lt;enumeration value="BA32"/>
 *             &lt;enumeration value="BA33"/>
 *             &lt;enumeration value="BA34"/>
 *             &lt;enumeration value="BA35"/>
 *             &lt;enumeration value="BA36"/>
 *             &lt;enumeration value="BA37"/>
 *             &lt;enumeration value="BA38"/>
 *             &lt;enumeration value="BA39"/>
 *             &lt;enumeration value="BA40"/>
 *             &lt;enumeration value="BA41"/>
 *             &lt;enumeration value="BA42"/>
 *             &lt;enumeration value="BA43"/>
 *             &lt;enumeration value="BA44"/>
 *             &lt;enumeration value="BA45"/>
 *             &lt;enumeration value="BA46"/>
 *             &lt;enumeration value="BA47"/>
 *             &lt;enumeration value="BA48"/>
 *             &lt;enumeration value="BA49"/>
 *             &lt;enumeration value="BA50"/>
 *             &lt;enumeration value="BA51"/>
 *             &lt;enumeration value="BA52"/>
 *             &lt;enumeration value="BA53"/>
 *             &lt;enumeration value="BA54"/>
 *             &lt;enumeration value="BB01"/>
 *             &lt;enumeration value="BB02"/>
 *             &lt;enumeration value="BB03"/>
 *             &lt;enumeration value="BB04"/>
 *             &lt;enumeration value="BB05"/>
 *             &lt;enumeration value="BB06"/>
 *             &lt;enumeration value="BB07"/>
 *             &lt;enumeration value="BC01"/>
 *             &lt;enumeration value="BC02"/>
 *             &lt;enumeration value="BC03"/>
 *             &lt;enumeration value="BC04"/>
 *             &lt;enumeration value="BC05"/>
 *             &lt;enumeration value="BC06"/>
 *             &lt;enumeration value="BC07"/>
 *             &lt;enumeration value="BC08"/>
 *             &lt;enumeration value="BC09"/>
 *             &lt;enumeration value="BC10"/>
 *             &lt;enumeration value="BC11"/>
 *             &lt;enumeration value="BC12"/>
 *             &lt;enumeration value="BC13"/>
 *             &lt;enumeration value="BC14"/>
 *             &lt;enumeration value="BC15"/>
 *             &lt;enumeration value="BC16"/>
 *             &lt;enumeration value="BC17"/>
 *             &lt;enumeration value="BC18"/>
 *             &lt;enumeration value="BC19"/>
 *             &lt;enumeration value="BC20"/>
 *             &lt;enumeration value="BC21"/>
 *             &lt;enumeration value="BC22"/>
 *             &lt;enumeration value="BC23"/>
 *             &lt;enumeration value="BC24"/>
 *             &lt;enumeration value="BC25"/>
 *             &lt;enumeration value="BC26"/>
 *             &lt;enumeration value="BC27"/>
 *             &lt;enumeration value="BC28"/>
 *             &lt;enumeration value="BC29"/>
 *             &lt;enumeration value="BC30"/>
 *             &lt;enumeration value="BC31"/>
 *             &lt;enumeration value="BC32"/>
 *             &lt;enumeration value="BC33"/>
 *             &lt;enumeration value="BC34"/>
 *             &lt;enumeration value="BC35"/>
 *             &lt;enumeration value="BC36"/>
 *             &lt;enumeration value="BC37"/>
 *             &lt;enumeration value="BC38"/>
 *             &lt;enumeration value="BC39"/>
 *             &lt;enumeration value="BC40"/>
 *             &lt;enumeration value="BC41"/>
 *             &lt;enumeration value="BC42"/>
 *             &lt;enumeration value="BC43"/>
 *             &lt;enumeration value="BC44"/>
 *             &lt;enumeration value="BC45"/>
 *             &lt;enumeration value="BC46"/>
 *             &lt;enumeration value="BC48"/>
 *             &lt;enumeration value="CA01"/>
 *             &lt;enumeration value="CA02"/>
 *             &lt;enumeration value="CA03"/>
 *             &lt;enumeration value="CA04"/>
 *             &lt;enumeration value="CA05"/>
 *             &lt;enumeration value="CA06"/>
 *             &lt;enumeration value="CA07"/>
 *             &lt;enumeration value="CA08"/>
 *             &lt;enumeration value="CA09"/>
 *             &lt;enumeration value="CA10"/>
 *             &lt;enumeration value="CA11"/>
 *             &lt;enumeration value="CA12"/>
 *             &lt;enumeration value="CA13"/>
 *             &lt;enumeration value="CA14"/>
 *             &lt;enumeration value="CA15"/>
 *             &lt;enumeration value="CA16"/>
 *             &lt;enumeration value="CA17"/>
 *             &lt;enumeration value="CA18"/>
 *             &lt;enumeration value="CA19"/>
 *             &lt;enumeration value="CA20"/>
 *             &lt;enumeration value="CA21"/>
 *             &lt;enumeration value="CA22"/>
 *             &lt;enumeration value="CA23"/>
 *             &lt;enumeration value="CA24"/>
 *             &lt;enumeration value="CA25"/>
 *             &lt;enumeration value="CA26"/>
 *             &lt;enumeration value="CA27"/>
 *             &lt;enumeration value="CA28"/>
 *             &lt;enumeration value="CA29"/>
 *             &lt;enumeration value="CA30"/>
 *             &lt;enumeration value="CA31"/>
 *             &lt;enumeration value="CA32"/>
 *             &lt;enumeration value="CA33"/>
 *             &lt;enumeration value="CA34"/>
 *             &lt;enumeration value="CA35"/>
 *             &lt;enumeration value="CA36"/>
 *             &lt;enumeration value="CA37"/>
 *             &lt;enumeration value="CA38"/>
 *             &lt;enumeration value="CA39"/>
 *             &lt;enumeration value="CA40"/>
 *             &lt;enumeration value="CA41"/>
 *             &lt;enumeration value="CA42"/>
 *             &lt;enumeration value="CA43"/>
 *             &lt;enumeration value="CA44"/>
 *             &lt;enumeration value="CA45"/>
 *             &lt;enumeration value="CA46"/>
 *             &lt;enumeration value="CA47"/>
 *             &lt;enumeration value="CA48"/>
 *             &lt;enumeration value="CA49"/>
 *             &lt;enumeration value="CA50"/>
 *             &lt;enumeration value="CA51"/>
 *             &lt;enumeration value="CA52"/>
 *             &lt;enumeration value="CA53"/>
 *             &lt;enumeration value="CA54"/>
 *             &lt;enumeration value="CA55"/>
 *             &lt;enumeration value="CA56"/>
 *             &lt;enumeration value="CA57"/>
 *             &lt;enumeration value="CA58"/>
 *             &lt;enumeration value="CA59"/>
 *             &lt;enumeration value="CA60"/>
 *             &lt;enumeration value="CA61"/>
 *             &lt;enumeration value="CA62"/>
 *             &lt;enumeration value="CA63"/>
 *             &lt;enumeration value="CA64"/>
 *             &lt;enumeration value="CA65"/>
 *             &lt;enumeration value="CA66"/>
 *             &lt;enumeration value="CA67"/>
 *             &lt;enumeration value="CA68"/>
 *             &lt;enumeration value="CA69"/>
 *             &lt;enumeration value="CB01"/>
 *             &lt;enumeration value="CB02"/>
 *             &lt;enumeration value="CB03"/>
 *             &lt;enumeration value="CB04"/>
 *             &lt;enumeration value="CB05"/>
 *             &lt;enumeration value="CB06"/>
 *             &lt;enumeration value="CB07"/>
 *             &lt;enumeration value="CB08"/>
 *             &lt;enumeration value="CB09"/>
 *             &lt;enumeration value="CB10"/>
 *             &lt;enumeration value="CB11"/>
 *             &lt;enumeration value="CB12"/>
 *             &lt;enumeration value="CB13"/>
 *             &lt;enumeration value="CB14"/>
 *             &lt;enumeration value="CB15"/>
 *             &lt;enumeration value="CB16"/>
 *             &lt;enumeration value="CB17"/>
 *             &lt;enumeration value="CB18"/>
 *             &lt;enumeration value="CB19"/>
 *             &lt;enumeration value="CB20"/>
 *             &lt;enumeration value="CB21"/>
 *             &lt;enumeration value="CB22"/>
 *             &lt;enumeration value="CB23"/>
 *             &lt;enumeration value="CB24"/>
 *             &lt;enumeration value="CB25"/>
 *             &lt;enumeration value="CB26"/>
 *             &lt;enumeration value="CB27"/>
 *             &lt;enumeration value="CB28"/>
 *             &lt;enumeration value="CB29"/>
 *             &lt;enumeration value="CB30"/>
 *             &lt;enumeration value="CB31"/>
 *             &lt;enumeration value="CB32"/>
 *             &lt;enumeration value="CB33"/>
 *             &lt;enumeration value="CB34"/>
 *             &lt;enumeration value="CB35"/>
 *             &lt;enumeration value="CB36"/>
 *             &lt;enumeration value="CB37"/>
 *             &lt;enumeration value="CB38"/>
 *             &lt;enumeration value="CB39"/>
 *             &lt;enumeration value="CB40"/>
 *             &lt;enumeration value="CB41"/>
 *             &lt;enumeration value="CB42"/>
 *             &lt;enumeration value="CB43"/>
 *             &lt;enumeration value="CB44"/>
 *             &lt;enumeration value="CB45"/>
 *             &lt;enumeration value="CB46"/>
 *             &lt;enumeration value="CB47"/>
 *             &lt;enumeration value="DA01"/>
 *             &lt;enumeration value="DA02"/>
 *             &lt;enumeration value="DA03"/>
 *             &lt;enumeration value="DA04"/>
 *             &lt;enumeration value="DA05"/>
 *             &lt;enumeration value="DA06"/>
 *             &lt;enumeration value="DA07"/>
 *             &lt;enumeration value="DA08"/>
 *             &lt;enumeration value="DA09"/>
 *             &lt;enumeration value="DA10"/>
 *             &lt;enumeration value="DA11"/>
 *             &lt;enumeration value="DA12"/>
 *             &lt;enumeration value="DA13"/>
 *             &lt;enumeration value="DA14"/>
 *             &lt;enumeration value="DA15"/>
 *             &lt;enumeration value="DA16"/>
 *             &lt;enumeration value="DA17"/>
 *             &lt;enumeration value="DA18"/>
 *             &lt;enumeration value="DA19"/>
 *             &lt;enumeration value="DA20"/>
 *             &lt;enumeration value="DA21"/>
 *             &lt;enumeration value="DA22"/>
 *             &lt;enumeration value="DA23"/>
 *             &lt;enumeration value="DA24"/>
 *             &lt;enumeration value="DA25"/>
 *             &lt;enumeration value="DA26"/>
 *             &lt;enumeration value="DA27"/>
 *             &lt;enumeration value="DA28"/>
 *             &lt;enumeration value="DA29"/>
 *             &lt;enumeration value="DA30"/>
 *             &lt;enumeration value="DA31"/>
 *             &lt;enumeration value="DA32"/>
 *             &lt;enumeration value="DA33"/>
 *             &lt;enumeration value="DA34"/>
 *             &lt;enumeration value="DA35"/>
 *             &lt;enumeration value="DA36"/>
 *             &lt;enumeration value="DA37"/>
 *             &lt;enumeration value="DA38"/>
 *             &lt;enumeration value="DA39"/>
 *             &lt;enumeration value="DA40"/>
 *             &lt;enumeration value="DA41"/>
 *             &lt;enumeration value="DA42"/>
 *             &lt;enumeration value="DA43"/>
 *             &lt;enumeration value="DA44"/>
 *             &lt;enumeration value="EA01"/>
 *             &lt;enumeration value="EA02"/>
 *             &lt;enumeration value="EA03"/>
 *             &lt;enumeration value="EA04"/>
 *             &lt;enumeration value="EA05"/>
 *             &lt;enumeration value="EA06"/>
 *             &lt;enumeration value="EA07"/>
 *             &lt;enumeration value="EA08"/>
 *             &lt;enumeration value="EA09"/>
 *             &lt;enumeration value="EA10"/>
 *             &lt;enumeration value="EA11"/>
 *             &lt;enumeration value="EA12"/>
 *             &lt;enumeration value="EA13"/>
 *             &lt;enumeration value="EA14"/>
 *             &lt;enumeration value="EA15"/>
 *             &lt;enumeration value="EA16"/>
 *             &lt;enumeration value="EA17"/>
 *             &lt;enumeration value="EA18"/>
 *             &lt;enumeration value="EA19"/>
 *             &lt;enumeration value="EA20"/>
 *             &lt;enumeration value="EA21"/>
 *             &lt;enumeration value="EA22"/>
 *             &lt;enumeration value="EA23"/>
 *             &lt;enumeration value="EA24"/>
 *             &lt;enumeration value="EA25"/>
 *             &lt;enumeration value="EA26"/>
 *             &lt;enumeration value="EA27"/>
 *             &lt;enumeration value="EA28"/>
 *             &lt;enumeration value="EA29"/>
 *             &lt;enumeration value="EA30"/>
 *             &lt;enumeration value="FA01"/>
 *             &lt;enumeration value="FA02"/>
 *             &lt;enumeration value="FA03"/>
 *             &lt;enumeration value="FA04"/>
 *             &lt;enumeration value="FB01"/>
 *             &lt;enumeration value="FB02"/>
 *             &lt;enumeration value="FB03"/>
 *             &lt;enumeration value="FB04"/>
 *             &lt;enumeration value="FB05"/>
 *             &lt;enumeration value="FB06"/>
 *             &lt;enumeration value="FB07"/>
 *             &lt;enumeration value="FB08"/>
 *             &lt;enumeration value="FB09"/>
 *             &lt;enumeration value="FB10"/>
 *             &lt;enumeration value="FB11"/>
 *             &lt;enumeration value="FB12"/>
 *             &lt;enumeration value="FB13"/>
 *             &lt;enumeration value="FC01"/>
 *             &lt;enumeration value="FC02"/>
 *             &lt;enumeration value="FC03"/>
 *             &lt;enumeration value="FD01"/>
 *             &lt;enumeration value="FD02"/>
 *             &lt;enumeration value="FD03"/>
 *             &lt;enumeration value="FD04"/>
 *             &lt;enumeration value="FD05"/>
 *             &lt;enumeration value="FE01"/>
 *             &lt;enumeration value="FE02"/>
 *             &lt;enumeration value="FE03"/>
 *             &lt;enumeration value="FF01"/>
 *             &lt;enumeration value="FF02"/>
 *             &lt;enumeration value="FG01"/>
 *             &lt;enumeration value="FG02"/>
 *             &lt;enumeration value="FG03"/>
 *             &lt;enumeration value="FG04"/>
 *             &lt;enumeration value="FG05"/>
 *             &lt;enumeration value="FG06"/>
 *             &lt;enumeration value="FG07"/>
 *             &lt;enumeration value="FG08"/>
 *             &lt;enumeration value="FG09"/>
 *             &lt;enumeration value="FG10"/>
 *             &lt;enumeration value="FG11"/>
 *             &lt;enumeration value="FG12"/>
 *             &lt;enumeration value="FG13"/>
 *             &lt;enumeration value="FG14"/>
 *             &lt;enumeration value="FG15"/>
 *             &lt;enumeration value="FG16"/>
 *             &lt;enumeration value="FG17"/>
 *             &lt;enumeration value="FG18"/>
 *             &lt;enumeration value="FG19"/>
 *             &lt;enumeration value="FG20"/>
 *             &lt;enumeration value="FG21"/>
 *             &lt;enumeration value="FG22"/>
 *             &lt;enumeration value="FG23"/>
 *             &lt;enumeration value="FG24"/>
 *             &lt;enumeration value="FG25"/>
 *             &lt;enumeration value="GA01"/>
 *             &lt;enumeration value="GA02"/>
 *             &lt;enumeration value="GA03"/>
 *             &lt;enumeration value="GA04"/>
 *             &lt;enumeration value="GA05"/>
 *             &lt;enumeration value="GA06"/>
 *             &lt;enumeration value="GA07"/>
 *             &lt;enumeration value="GA08"/>
 *             &lt;enumeration value="GA09"/>
 *             &lt;enumeration value="GA10"/>
 *             &lt;enumeration value="GA11"/>
 *             &lt;enumeration value="GA12"/>
 *             &lt;enumeration value="GA13"/>
 *             &lt;enumeration value="GA14"/>
 *             &lt;enumeration value="GA15"/>
 *             &lt;enumeration value="GA16"/>
 *             &lt;enumeration value="GA17"/>
 *             &lt;enumeration value="GA18"/>
 *             &lt;enumeration value="GA19"/>
 *             &lt;enumeration value="GA20"/>
 *             &lt;enumeration value="GA21"/>
 *             &lt;enumeration value="GA22"/>
 *             &lt;enumeration value="GA32"/>
 *             &lt;enumeration value="GA33"/>
 *             &lt;enumeration value="GB01"/>
 *             &lt;enumeration value="GB02"/>
 *             &lt;enumeration value="GB03"/>
 *             &lt;enumeration value="GB04"/>
 *             &lt;enumeration value="GC01"/>
 *             &lt;enumeration value="GC02"/>
 *             &lt;enumeration value="GC03"/>
 *             &lt;enumeration value="GC04"/>
 *             &lt;enumeration value="GC05"/>
 *             &lt;enumeration value="GC06"/>
 *             &lt;enumeration value="GC07"/>
 *             &lt;enumeration value="GC08"/>
 *             &lt;enumeration value="GC09"/>
 *             &lt;enumeration value="GC10"/>
 *             &lt;enumeration value="GC11"/>
 *             &lt;enumeration value="GC12"/>
 *             &lt;enumeration value="GC13"/>
 *             &lt;enumeration value="GC14"/>
 *             &lt;enumeration value="GC15"/>
 *             &lt;enumeration value="GC16"/>
 *             &lt;enumeration value="GC17"/>
 *             &lt;enumeration value="GC18"/>
 *             &lt;enumeration value="GC19"/>
 *             &lt;enumeration value="GC20"/>
 *             &lt;enumeration value="GC21"/>
 *             &lt;enumeration value="GC22"/>
 *             &lt;enumeration value="GC23"/>
 *             &lt;enumeration value="GC24"/>
 *             &lt;enumeration value="GC25"/>
 *             &lt;enumeration value="GC26"/>
 *             &lt;enumeration value="GC27"/>
 *             &lt;enumeration value="GC28"/>
 *             &lt;enumeration value="GC29"/>
 *             &lt;enumeration value="GC30"/>
 *             &lt;enumeration value="GC31"/>
 *             &lt;enumeration value="GC32"/>
 *             &lt;enumeration value="GC33"/>
 *             &lt;enumeration value="GC34"/>
 *             &lt;enumeration value="HA01"/>
 *             &lt;enumeration value="HA02"/>
 *             &lt;enumeration value="HA03"/>
 *             &lt;enumeration value="HA04"/>
 *             &lt;enumeration value="HA05"/>
 *             &lt;enumeration value="HA06"/>
 *             &lt;enumeration value="HA07"/>
 *             &lt;enumeration value="HA08"/>
 *             &lt;enumeration value="HA09"/>
 *             &lt;enumeration value="HA10"/>
 *             &lt;enumeration value="HA11"/>
 *             &lt;enumeration value="HA12"/>
 *             &lt;enumeration value="HA13"/>
 *             &lt;enumeration value="HA14"/>
 *             &lt;enumeration value="HA15"/>
 *             &lt;enumeration value="HA16"/>
 *             &lt;enumeration value="HA17"/>
 *             &lt;enumeration value="HA18"/>
 *             &lt;enumeration value="HA19"/>
 *             &lt;enumeration value="HA20"/>
 *             &lt;enumeration value="HA21"/>
 *             &lt;enumeration value="HA22"/>
 *             &lt;enumeration value="HA23"/>
 *             &lt;enumeration value="HA24"/>
 *             &lt;enumeration value="HA25"/>
 *             &lt;enumeration value="HA26"/>
 *             &lt;enumeration value="HA27"/>
 *             &lt;enumeration value="HA28"/>
 *             &lt;enumeration value="HA29"/>
 *             &lt;enumeration value="HA30"/>
 *             &lt;enumeration value="HA31"/>
 *             &lt;enumeration value="IA01"/>
 *             &lt;enumeration value="IA02"/>
 *             &lt;enumeration value="IA03"/>
 *             &lt;enumeration value="IA04"/>
 *             &lt;enumeration value="IA05"/>
 *             &lt;enumeration value="IA06"/>
 *             &lt;enumeration value="IA07"/>
 *             &lt;enumeration value="IA08"/>
 *             &lt;enumeration value="IA09"/>
 *             &lt;enumeration value="IA10"/>
 *             &lt;enumeration value="IA11"/>
 *             &lt;enumeration value="IA13"/>
 *             &lt;enumeration value="IA14"/>
 *             &lt;enumeration value="IA15"/>
 *             &lt;enumeration value="IA16"/>
 *             &lt;enumeration value="IA17"/>
 *             &lt;enumeration value="IA18"/>
 *             &lt;enumeration value="IA19"/>
 *             &lt;enumeration value="IA20"/>
 *             &lt;enumeration value="IA21"/>
 *             &lt;enumeration value="IA22"/>
 *             &lt;enumeration value="IA23"/>
 *             &lt;enumeration value="IA24"/>
 *             &lt;enumeration value="IA25"/>
 *             &lt;enumeration value="IA26"/>
 *             &lt;enumeration value="IA27"/>
 *             &lt;enumeration value="IA28"/>
 *             &lt;enumeration value="IA29"/>
 *             &lt;enumeration value="IA30"/>
 *             &lt;enumeration value="IA31"/>
 *             &lt;enumeration value="IA32"/>
 *             &lt;enumeration value="IA33"/>
 *             &lt;enumeration value="IA34"/>
 *             &lt;enumeration value="IA35"/>
 *             &lt;enumeration value="IA36"/>
 *             &lt;enumeration value="IA37"/>
 *             &lt;enumeration value="IA38"/>
 *             &lt;enumeration value="IA39"/>
 *             &lt;enumeration value="IA40"/>
 *             &lt;enumeration value="IA41"/>
 *             &lt;enumeration value="IA42"/>
 *             &lt;enumeration value="JA01"/>
 *             &lt;enumeration value="JA02"/>
 *             &lt;enumeration value="JA03"/>
 *             &lt;enumeration value="JA04"/>
 *             &lt;enumeration value="JA05"/>
 *             &lt;enumeration value="JA06"/>
 *             &lt;enumeration value="JA07"/>
 *             &lt;enumeration value="JA08"/>
 *             &lt;enumeration value="JA09"/>
 *             &lt;enumeration value="JA10"/>
 *             &lt;enumeration value="JA11"/>
 *             &lt;enumeration value="JA12"/>
 *             &lt;enumeration value="JA13"/>
 *             &lt;enumeration value="JA14"/>
 *             &lt;enumeration value="JA15"/>
 *             &lt;enumeration value="JA16"/>
 *             &lt;enumeration value="JA17"/>
 *             &lt;enumeration value="JA18"/>
 *             &lt;enumeration value="JA19"/>
 *             &lt;enumeration value="JA20"/>
 *             &lt;enumeration value="JA21"/>
 *             &lt;enumeration value="JA22"/>
 *             &lt;enumeration value="JA23"/>
 *             &lt;enumeration value="JA24"/>
 *             &lt;enumeration value="KA01"/>
 *             &lt;enumeration value="KA02"/>
 *             &lt;enumeration value="KA03"/>
 *             &lt;enumeration value="KA04"/>
 *             &lt;enumeration value="KA05"/>
 *             &lt;enumeration value="KA06"/>
 *             &lt;enumeration value="KA07"/>
 *             &lt;enumeration value="KA08"/>
 *             &lt;enumeration value="KA09"/>
 *             &lt;enumeration value="KA10"/>
 *             &lt;enumeration value="KA11"/>
 *             &lt;enumeration value="KA12"/>
 *             &lt;enumeration value="KA13"/>
 *             &lt;enumeration value="KA14"/>
 *             &lt;enumeration value="KA15"/>
 *             &lt;enumeration value="KA16"/>
 *             &lt;enumeration value="LA01"/>
 *             &lt;enumeration value="LA02"/>
 *             &lt;enumeration value="LA03"/>
 *             &lt;enumeration value="LA04"/>
 *             &lt;enumeration value="LA05"/>
 *             &lt;enumeration value="LA06"/>
 *             &lt;enumeration value="LA07"/>
 *             &lt;enumeration value="LA08"/>
 *             &lt;enumeration value="LA09"/>
 *             &lt;enumeration value="LA10"/>
 *             &lt;enumeration value="LA11"/>
 *             &lt;enumeration value="LA12"/>
 *             &lt;enumeration value="LA13"/>
 *             &lt;enumeration value="LA14"/>
 *             &lt;enumeration value="LA15"/>
 *             &lt;enumeration value="LA16"/>
 *             &lt;enumeration value="LA17"/>
 *             &lt;enumeration value="LA18"/>
 *             &lt;enumeration value="LA19"/>
 *             &lt;enumeration value="LA20"/>
 *             &lt;enumeration value="LA21"/>
 *             &lt;enumeration value="LA22"/>
 *             &lt;enumeration value="LA23"/>
 *             &lt;enumeration value="LA24"/>
 *             &lt;enumeration value="LA25"/>
 *             &lt;enumeration value="LA26"/>
 *             &lt;enumeration value="LA27"/>
 *             &lt;enumeration value="LA28"/>
 *             &lt;enumeration value="LA29"/>
 *             &lt;enumeration value="LA30"/>
 *             &lt;enumeration value="LA31"/>
 *             &lt;enumeration value="LA32"/>
 *             &lt;enumeration value="LA33"/>
 *             &lt;enumeration value="LA34"/>
 *             &lt;enumeration value="LA35"/>
 *             &lt;enumeration value="LA36"/>
 *             &lt;enumeration value="LA37"/>
 *             &lt;enumeration value="LA38"/>
 *             &lt;enumeration value="LA39"/>
 *             &lt;enumeration value="LA40"/>
 *             &lt;enumeration value="LA41"/>
 *             &lt;enumeration value="LA42"/>
 *             &lt;enumeration value="LA43"/>
 *             &lt;enumeration value="LA44"/>
 *             &lt;enumeration value="LA45"/>
 *             &lt;enumeration value="LA46"/>
 *             &lt;enumeration value="LA47"/>
 *             &lt;enumeration value="LA48"/>
 *             &lt;enumeration value="LA49"/>
 *             &lt;enumeration value="LA50"/>
 *             &lt;enumeration value="LA51"/>
 *             &lt;enumeration value="LA52"/>
 *             &lt;enumeration value="LA53"/>
 *             &lt;enumeration value="LA54"/>
 *             &lt;enumeration value="LA55"/>
 *             &lt;enumeration value="MA01"/>
 *             &lt;enumeration value="MA02"/>
 *             &lt;enumeration value="MA03"/>
 *             &lt;enumeration value="MA04"/>
 *             &lt;enumeration value="MA05"/>
 *             &lt;enumeration value="MA06"/>
 *             &lt;enumeration value="MA07"/>
 *             &lt;enumeration value="MA08"/>
 *             &lt;enumeration value="MA09"/>
 *             &lt;enumeration value="MA10"/>
 *             &lt;enumeration value="MA11"/>
 *             &lt;enumeration value="MA12"/>
 *             &lt;enumeration value="MA13"/>
 *             &lt;enumeration value="MA14"/>
 *             &lt;enumeration value="MB01"/>
 *             &lt;enumeration value="MB02"/>
 *             &lt;enumeration value="MB03"/>
 *             &lt;enumeration value="MB04"/>
 *             &lt;enumeration value="MD01"/>
 *             &lt;enumeration value="MD02"/>
 *             &lt;enumeration value="MD03"/>
 *             &lt;enumeration value="MD04"/>
 *             &lt;enumeration value="MD05"/>
 *             &lt;enumeration value="MD06"/>
 *             &lt;enumeration value="MD07"/>
 *             &lt;enumeration value="ME01"/>
 *             &lt;enumeration value="ME02"/>
 *             &lt;enumeration value="ME03"/>
 *             &lt;enumeration value="ME04"/>
 *             &lt;enumeration value="ME05"/>
 *             &lt;enumeration value="MF01"/>
 *             &lt;enumeration value="MF02"/>
 *             &lt;enumeration value="MF03"/>
 *             &lt;enumeration value="MF04"/>
 *             &lt;enumeration value="MF05"/>
 *             &lt;enumeration value="MF06"/>
 *             &lt;enumeration value="MF07"/>
 *             &lt;enumeration value="MF08"/>
 *             &lt;enumeration value="MF09"/>
 *             &lt;enumeration value="MF10"/>
 *             &lt;enumeration value="PA01"/>
 *             &lt;enumeration value="PA02"/>
 *             &lt;enumeration value="PA03"/>
 *             &lt;enumeration value="PB01"/>
 *             &lt;enumeration value="PB02"/>
 *             &lt;enumeration value="PB03"/>
 *             &lt;enumeration value="PB04"/>
 *             &lt;enumeration value="PB05"/>
 *             &lt;enumeration value="PB06"/>
 *             &lt;enumeration value="QA01"/>
 *             &lt;enumeration value="QA02"/>
 *             &lt;enumeration value="QA03"/>
 *             &lt;enumeration value="QA04"/>
 *             &lt;enumeration value="QA05"/>
 *             &lt;enumeration value="QA06"/>
 *             &lt;enumeration value="QA07"/>
 *             &lt;enumeration value="QA08"/>
 *             &lt;enumeration value="QA09"/>
 *             &lt;enumeration value="QA10"/>
 *             &lt;enumeration value="QA11"/>
 *             &lt;enumeration value="QA12"/>
 *             &lt;enumeration value="QA13"/>
 *             &lt;enumeration value="QB01"/>
 *             &lt;enumeration value="QB02"/>
 *             &lt;enumeration value="QB03"/>
 *             &lt;enumeration value="QB04"/>
 *             &lt;enumeration value="QB05"/>
 *             &lt;enumeration value="QB06"/>
 *             &lt;enumeration value="QB07"/>
 *             &lt;enumeration value="QB08"/>
 *             &lt;enumeration value="QB09"/>
 *             &lt;enumeration value="QB10"/>
 *             &lt;enumeration value="QB11"/>
 *             &lt;enumeration value="QB12"/>
 *             &lt;enumeration value="QB13"/>
 *             &lt;enumeration value="QB14"/>
 *             &lt;enumeration value="QB15"/>
 *             &lt;enumeration value="QB16"/>
 *             &lt;enumeration value="QB17"/>
 *             &lt;enumeration value="QB18"/>
 *             &lt;enumeration value="QB19"/>
 *             &lt;enumeration value="QB20"/>
 *             &lt;enumeration value="QB21"/>
 *             &lt;enumeration value="QB23"/>
 *             &lt;enumeration value="QB24"/>
 *             &lt;enumeration value="QB25"/>
 *             &lt;enumeration value="QB26"/>
 *             &lt;enumeration value="QB27"/>
 *             &lt;enumeration value="QB28"/>
 *             &lt;enumeration value="QB29"/>
 *             &lt;enumeration value="QB30"/>
 *             &lt;enumeration value="QB31"/>
 *             &lt;enumeration value="QB32"/>
 *             &lt;enumeration value="QB33"/>
 *             &lt;enumeration value="QB34"/>
 *             &lt;enumeration value="QB35"/>
 *             &lt;enumeration value="QB36"/>
 *             &lt;enumeration value="QB37"/>
 *             &lt;enumeration value="QB38"/>
 *             &lt;enumeration value="QB39"/>
 *             &lt;enumeration value="QB40"/>
 *             &lt;enumeration value="QB41"/>
 *             &lt;enumeration value="QB42"/>
 *             &lt;enumeration value="QB43"/>
 *             &lt;enumeration value="QB44"/>
 *             &lt;enumeration value="QB45"/>
 *             &lt;enumeration value="QB46"/>
 *             &lt;enumeration value="QB47"/>
 *             &lt;enumeration value="QB48"/>
 *             &lt;enumeration value="QB49"/>
 *             &lt;enumeration value="QB50"/>
 *             &lt;enumeration value="QB51"/>
 *             &lt;enumeration value="QB52"/>
 *             &lt;enumeration value="QB53"/>
 *             &lt;enumeration value="QB54"/>
 *             &lt;enumeration value="QB55"/>
 *             &lt;enumeration value="QB56"/>
 *             &lt;enumeration value="QB57"/>
 *             &lt;enumeration value="RA01"/>
 *             &lt;enumeration value="RA02"/>
 *             &lt;enumeration value="RA03"/>
 *             &lt;enumeration value="RA04"/>
 *             &lt;enumeration value="RA05"/>
 *             &lt;enumeration value="RA06"/>
 *             &lt;enumeration value="RA07"/>
 *             &lt;enumeration value="RA08"/>
 *             &lt;enumeration value="RA09"/>
 *             &lt;enumeration value="RA10"/>
 *             &lt;enumeration value="RA11"/>
 *             &lt;enumeration value="RA12"/>
 *             &lt;enumeration value="RA13"/>
 *             &lt;enumeration value="RA14"/>
 *             &lt;enumeration value="RA15"/>
 *             &lt;enumeration value="RA16"/>
 *             &lt;enumeration value="RB01"/>
 *             &lt;enumeration value="RB02"/>
 *             &lt;enumeration value="RB03"/>
 *             &lt;enumeration value="RB04"/>
 *             &lt;enumeration value="RB05"/>
 *             &lt;enumeration value="RB06"/>
 *             &lt;enumeration value="RB07"/>
 *             &lt;enumeration value="RB08"/>
 *             &lt;enumeration value="RB09"/>
 *             &lt;enumeration value="RB10"/>
 *             &lt;enumeration value="RB11"/>
 *             &lt;enumeration value="RB12"/>
 *             &lt;enumeration value="RB13"/>
 *             &lt;enumeration value="RB14"/>
 *             &lt;enumeration value="RB15"/>
 *             &lt;enumeration value="RB16"/>
 *             &lt;enumeration value="RB17"/>
 *             &lt;enumeration value="RB18"/>
 *             &lt;enumeration value="RB19"/>
 *             &lt;enumeration value="RB20"/>
 *             &lt;enumeration value="RB21"/>
 *             &lt;enumeration value="RC01"/>
 *             &lt;enumeration value="RC02"/>
 *             &lt;enumeration value="RC03"/>
 *             &lt;enumeration value="RC04"/>
 *             &lt;enumeration value="RC05"/>
 *             &lt;enumeration value="RC06"/>
 *             &lt;enumeration value="RC07"/>
 *             &lt;enumeration value="RC08"/>
 *             &lt;enumeration value="RD01"/>
 *             &lt;enumeration value="RD02"/>
 *             &lt;enumeration value="RD03"/>
 *             &lt;enumeration value="RD04"/>
 *             &lt;enumeration value="RD05"/>
 *             &lt;enumeration value="RD06"/>
 *             &lt;enumeration value="RD07"/>
 *             &lt;enumeration value="RD08"/>
 *             &lt;enumeration value="RD09"/>
 *             &lt;enumeration value="RD10"/>
 *             &lt;enumeration value="RD11"/>
 *             &lt;enumeration value="SA01"/>
 *             &lt;enumeration value="SA02"/>
 *             &lt;enumeration value="SA03"/>
 *             &lt;enumeration value="SA04"/>
 *             &lt;enumeration value="SB01"/>
 *             &lt;enumeration value="SB02"/>
 *             &lt;enumeration value="SC01"/>
 *             &lt;enumeration value="TA01"/>
 *             &lt;enumeration value="TA02"/>
 *             &lt;enumeration value="TA03"/>
 *             &lt;enumeration value="TA04"/>
 *             &lt;enumeration value="TA05"/>
 *             &lt;enumeration value="TA06"/>
 *             &lt;enumeration value="TA07"/>
 *             &lt;enumeration value="TA08"/>
 *             &lt;enumeration value="TA09"/>
 *             &lt;enumeration value="TA10"/>
 *             &lt;enumeration value="TA11"/>
 *             &lt;enumeration value="TA12"/>
 *             &lt;enumeration value="TA13"/>
 *             &lt;enumeration value="TA14"/>
 *             &lt;enumeration value="TA15"/>
 *             &lt;enumeration value="TA16"/>
 *             &lt;enumeration value="TA17"/>
 *             &lt;enumeration value="TA18"/>
 *             &lt;enumeration value="TA19"/>
 *             &lt;enumeration value="TA20"/>
 *             &lt;enumeration value="TA21"/>
 *             &lt;enumeration value="TA22"/>
 *             &lt;enumeration value="TA23"/>
 *             &lt;enumeration value="TA24"/>
 *             &lt;enumeration value="TA25"/>
 *             &lt;enumeration value="TA26"/>
 *             &lt;enumeration value="TA27"/>
 *             &lt;enumeration value="TA28"/>
 *             &lt;enumeration value="TA29"/>
 *             &lt;enumeration value="TA30"/>
 *             &lt;enumeration value="TA31"/>
 *             &lt;enumeration value="TA32"/>
 *             &lt;enumeration value="TA33"/>
 *             &lt;enumeration value="TA34"/>
 *             &lt;enumeration value="TA35"/>
 *             &lt;enumeration value="TA36"/>
 *             &lt;enumeration value="TA37"/>
 *             &lt;enumeration value="TA38"/>
 *             &lt;enumeration value="TA39"/>
 *             &lt;enumeration value="TA40"/>
 *             &lt;enumeration value="TA41"/>
 *             &lt;enumeration value="TA42"/>
 *             &lt;enumeration value="TA43"/>
 *             &lt;enumeration value="TA44"/>
 *             &lt;enumeration value="TA45"/>
 *             &lt;enumeration value="TA46"/>
 *             &lt;enumeration value="TA47"/>
 *             &lt;enumeration value="TA48"/>
 *             &lt;enumeration value="UA01"/>
 *             &lt;enumeration value="UA02"/>
 *             &lt;enumeration value="UB01"/>
 *             &lt;enumeration value="UB02"/>
 *             &lt;enumeration value="UB03"/>
 *             &lt;enumeration value="UB04"/>
 *             &lt;enumeration value="UB05"/>
 *             &lt;enumeration value="UB06"/>
 *             &lt;enumeration value="UB07"/>
 *             &lt;enumeration value="UB08"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "cpv_supplementary_codes")
@XmlRootElement(name = "CPV_SUPPLEMENTARY_CODE")
public class CPVSUPPLEMENTARYCODE
    implements Equals, HashCode, ToString
{

    @XmlAttribute(name = "CODE", required = true)
    protected String code;

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCODE() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCODE(String value) {
        this.code = value;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof CPVSUPPLEMENTARYCODE)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final CPVSUPPLEMENTARYCODE that = ((CPVSUPPLEMENTARYCODE) object);
        {
            String lhsCODE;
            lhsCODE = this.getCODE();
            String rhsCODE;
            rhsCODE = that.getCODE();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "code", lhsCODE), LocatorUtils.property(thatLocator, "code", rhsCODE), lhsCODE, rhsCODE)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = 1;
        {
            String theCODE;
            theCODE = this.getCODE();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "code", theCODE), currentHashCode, theCODE);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        {
            String theCODE;
            theCODE = this.getCODE();
            strategy.appendField(locator, this, "code", buffer, theCODE);
        }
        return buffer;
    }

}
