//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.04 at 01:40:50 PM MEZ 
//


package eu.europa.publications.formex.ted.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for object_f07 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="object_f07">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://formex.publications.europa.eu/ted/schema/reception/R2.0.9.S01}CPV_ADDITIONAL" maxOccurs="20" minOccurs="0"/>
 *         &lt;element ref="{http://formex.publications.europa.eu/ted/schema/reception/R2.0.9.S01}NUTS" maxOccurs="20"/>
 *         &lt;element ref="{http://formex.publications.europa.eu/ted/schema/reception/R2.0.9.S01}MAIN_SITE" minOccurs="0"/>
 *         &lt;element ref="{http://formex.publications.europa.eu/ted/schema/reception/R2.0.9.S01}SHORT_DESCR"/>
 *         &lt;group ref="{http://formex.publications.europa.eu/ted/schema/reception/R2.0.9.S01}award_criteria_doc" minOccurs="0"/>
 *         &lt;group ref="{http://formex.publications.europa.eu/ted/schema/reception/R2.0.9.S01}time_frame_indefinite"/>
 *         &lt;sequence minOccurs="0">
 *           &lt;element ref="{http://formex.publications.europa.eu/ted/schema/reception/R2.0.9.S01}RENEWAL"/>
 *           &lt;element ref="{http://formex.publications.europa.eu/ted/schema/reception/R2.0.9.S01}RENEWAL_DESCR" minOccurs="0"/>
 *         &lt;/sequence>
 *         &lt;group ref="{http://formex.publications.europa.eu/ted/schema/reception/R2.0.9.S01}eu_union_funds" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "object_f07", propOrder = {
    "cpvadditionals",
    "nuts",
    "mainsite",
    "shortdescr",
    "acprocurementdoc",
    "acqualities",
    "acprice",
    "accosts",
    "datestart",
    "dateend",
    "indefiniteduration",
    "renewal",
    "renewaldescr",
    "noeuprogrrelated",
    "euprogrrelated"
})
public class ObjectF07
    implements Equals, HashCode, ToString
{

    @XmlElement(name = "CPV_ADDITIONAL")
    protected List<CpvSet> cpvadditionals;
    @XmlElement(name = "NUTS", required = true)
    protected List<NUTS> nuts;
    @XmlElement(name = "MAIN_SITE")
    protected TextFtMultiLines mainsite;
    @XmlElement(name = "SHORT_DESCR", required = true)
    protected TextFtMultiLines shortdescr;
    @XmlElement(name = "AC_PROCUREMENT_DOC")
    protected Empty acprocurementdoc;
    @XmlElement(name = "AC_QUALITY")
    protected List<AcDefinition> acqualities;
    @XmlElement(name = "AC_PRICE")
    protected ACPRICE acprice;
    @XmlElement(name = "AC_COST")
    protected List<AcDefinition> accosts;
    @XmlElement(name = "DATE_START")
    protected XMLGregorianCalendar datestart;
    @XmlElement(name = "DATE_END")
    protected XMLGregorianCalendar dateend;
    @XmlElement(name = "INDEFINITE_DURATION")
    protected Empty indefiniteduration;
    @XmlElement(name = "RENEWAL")
    protected Empty renewal;
    @XmlElement(name = "RENEWAL_DESCR")
    protected TextFtMultiLines renewaldescr;
    @XmlElement(name = "NO_EU_PROGR_RELATED")
    protected Empty noeuprogrrelated;
    @XmlElement(name = "EU_PROGR_RELATED")
    protected String euprogrrelated;

    /**
     * Gets the value of the cpvadditionals property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cpvadditionals property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCPVADDITIONALS().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CpvSet }
     * 
     * 
     */
    public List<CpvSet> getCPVADDITIONALS() {
        if (cpvadditionals == null) {
            cpvadditionals = new ArrayList<CpvSet>();
        }
        return this.cpvadditionals;
    }

    /**
     * Gets the value of the nuts property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nuts property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNUTS().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NUTS }
     * 
     * 
     */
    public List<NUTS> getNUTS() {
        if (nuts == null) {
            nuts = new ArrayList<NUTS>();
        }
        return this.nuts;
    }

    /**
     * Gets the value of the mainsite property.
     * 
     * @return
     *     possible object is
     *     {@link TextFtMultiLines }
     *     
     */
    public TextFtMultiLines getMAINSITE() {
        return mainsite;
    }

    /**
     * Sets the value of the mainsite property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextFtMultiLines }
     *     
     */
    public void setMAINSITE(TextFtMultiLines value) {
        this.mainsite = value;
    }

    /**
     * Gets the value of the shortdescr property.
     * 
     * @return
     *     possible object is
     *     {@link TextFtMultiLines }
     *     
     */
    public TextFtMultiLines getSHORTDESCR() {
        return shortdescr;
    }

    /**
     * Sets the value of the shortdescr property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextFtMultiLines }
     *     
     */
    public void setSHORTDESCR(TextFtMultiLines value) {
        this.shortdescr = value;
    }

    /**
     * Gets the value of the acprocurementdoc property.
     * 
     * @return
     *     possible object is
     *     {@link Empty }
     *     
     */
    public Empty getACPROCUREMENTDOC() {
        return acprocurementdoc;
    }

    /**
     * Sets the value of the acprocurementdoc property.
     * 
     * @param value
     *     allowed object is
     *     {@link Empty }
     *     
     */
    public void setACPROCUREMENTDOC(Empty value) {
        this.acprocurementdoc = value;
    }

    /**
     * Gets the value of the acqualities property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the acqualities property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getACQUALITIES().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AcDefinition }
     * 
     * 
     */
    public List<AcDefinition> getACQUALITIES() {
        if (acqualities == null) {
            acqualities = new ArrayList<AcDefinition>();
        }
        return this.acqualities;
    }

    /**
     * Gets the value of the acprice property.
     * 
     * @return
     *     possible object is
     *     {@link ACPRICE }
     *     
     */
    public ACPRICE getACPRICE() {
        return acprice;
    }

    /**
     * Sets the value of the acprice property.
     * 
     * @param value
     *     allowed object is
     *     {@link ACPRICE }
     *     
     */
    public void setACPRICE(ACPRICE value) {
        this.acprice = value;
    }

    /**
     * Gets the value of the accosts property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the accosts property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getACCOSTS().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AcDefinition }
     * 
     * 
     */
    public List<AcDefinition> getACCOSTS() {
        if (accosts == null) {
            accosts = new ArrayList<AcDefinition>();
        }
        return this.accosts;
    }

    /**
     * Gets the value of the datestart property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDATESTART() {
        return datestart;
    }

    /**
     * Sets the value of the datestart property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDATESTART(XMLGregorianCalendar value) {
        this.datestart = value;
    }

    /**
     * Gets the value of the dateend property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDATEEND() {
        return dateend;
    }

    /**
     * Sets the value of the dateend property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDATEEND(XMLGregorianCalendar value) {
        this.dateend = value;
    }

    /**
     * Gets the value of the indefiniteduration property.
     * 
     * @return
     *     possible object is
     *     {@link Empty }
     *     
     */
    public Empty getINDEFINITEDURATION() {
        return indefiniteduration;
    }

    /**
     * Sets the value of the indefiniteduration property.
     * 
     * @param value
     *     allowed object is
     *     {@link Empty }
     *     
     */
    public void setINDEFINITEDURATION(Empty value) {
        this.indefiniteduration = value;
    }

    /**
     * Gets the value of the renewal property.
     * 
     * @return
     *     possible object is
     *     {@link Empty }
     *     
     */
    public Empty getRENEWAL() {
        return renewal;
    }

    /**
     * Sets the value of the renewal property.
     * 
     * @param value
     *     allowed object is
     *     {@link Empty }
     *     
     */
    public void setRENEWAL(Empty value) {
        this.renewal = value;
    }

    /**
     * Gets the value of the renewaldescr property.
     * 
     * @return
     *     possible object is
     *     {@link TextFtMultiLines }
     *     
     */
    public TextFtMultiLines getRENEWALDESCR() {
        return renewaldescr;
    }

    /**
     * Sets the value of the renewaldescr property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextFtMultiLines }
     *     
     */
    public void setRENEWALDESCR(TextFtMultiLines value) {
        this.renewaldescr = value;
    }

    /**
     * Gets the value of the noeuprogrrelated property.
     * 
     * @return
     *     possible object is
     *     {@link Empty }
     *     
     */
    public Empty getNOEUPROGRRELATED() {
        return noeuprogrrelated;
    }

    /**
     * Sets the value of the noeuprogrrelated property.
     * 
     * @param value
     *     allowed object is
     *     {@link Empty }
     *     
     */
    public void setNOEUPROGRRELATED(Empty value) {
        this.noeuprogrrelated = value;
    }

    /**
     * Gets the value of the euprogrrelated property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEUPROGRRELATED() {
        return euprogrrelated;
    }

    /**
     * Sets the value of the euprogrrelated property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEUPROGRRELATED(String value) {
        this.euprogrrelated = value;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof ObjectF07)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final ObjectF07 that = ((ObjectF07) object);
        {
            List<CpvSet> lhsCPVADDITIONALS;
            lhsCPVADDITIONALS = (((this.cpvadditionals!= null)&&(!this.cpvadditionals.isEmpty()))?this.getCPVADDITIONALS():null);
            List<CpvSet> rhsCPVADDITIONALS;
            rhsCPVADDITIONALS = (((that.cpvadditionals!= null)&&(!that.cpvadditionals.isEmpty()))?that.getCPVADDITIONALS():null);
            if (!strategy.equals(LocatorUtils.property(thisLocator, "cpvadditionals", lhsCPVADDITIONALS), LocatorUtils.property(thatLocator, "cpvadditionals", rhsCPVADDITIONALS), lhsCPVADDITIONALS, rhsCPVADDITIONALS)) {
                return false;
            }
        }
        {
            List<NUTS> lhsNUTS;
            lhsNUTS = (((this.nuts!= null)&&(!this.nuts.isEmpty()))?this.getNUTS():null);
            List<NUTS> rhsNUTS;
            rhsNUTS = (((that.nuts!= null)&&(!that.nuts.isEmpty()))?that.getNUTS():null);
            if (!strategy.equals(LocatorUtils.property(thisLocator, "nuts", lhsNUTS), LocatorUtils.property(thatLocator, "nuts", rhsNUTS), lhsNUTS, rhsNUTS)) {
                return false;
            }
        }
        {
            TextFtMultiLines lhsMAINSITE;
            lhsMAINSITE = this.getMAINSITE();
            TextFtMultiLines rhsMAINSITE;
            rhsMAINSITE = that.getMAINSITE();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "mainsite", lhsMAINSITE), LocatorUtils.property(thatLocator, "mainsite", rhsMAINSITE), lhsMAINSITE, rhsMAINSITE)) {
                return false;
            }
        }
        {
            TextFtMultiLines lhsSHORTDESCR;
            lhsSHORTDESCR = this.getSHORTDESCR();
            TextFtMultiLines rhsSHORTDESCR;
            rhsSHORTDESCR = that.getSHORTDESCR();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "shortdescr", lhsSHORTDESCR), LocatorUtils.property(thatLocator, "shortdescr", rhsSHORTDESCR), lhsSHORTDESCR, rhsSHORTDESCR)) {
                return false;
            }
        }
        {
            Empty lhsACPROCUREMENTDOC;
            lhsACPROCUREMENTDOC = this.getACPROCUREMENTDOC();
            Empty rhsACPROCUREMENTDOC;
            rhsACPROCUREMENTDOC = that.getACPROCUREMENTDOC();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "acprocurementdoc", lhsACPROCUREMENTDOC), LocatorUtils.property(thatLocator, "acprocurementdoc", rhsACPROCUREMENTDOC), lhsACPROCUREMENTDOC, rhsACPROCUREMENTDOC)) {
                return false;
            }
        }
        {
            List<AcDefinition> lhsACQUALITIES;
            lhsACQUALITIES = (((this.acqualities!= null)&&(!this.acqualities.isEmpty()))?this.getACQUALITIES():null);
            List<AcDefinition> rhsACQUALITIES;
            rhsACQUALITIES = (((that.acqualities!= null)&&(!that.acqualities.isEmpty()))?that.getACQUALITIES():null);
            if (!strategy.equals(LocatorUtils.property(thisLocator, "acqualities", lhsACQUALITIES), LocatorUtils.property(thatLocator, "acqualities", rhsACQUALITIES), lhsACQUALITIES, rhsACQUALITIES)) {
                return false;
            }
        }
        {
            ACPRICE lhsACPRICE;
            lhsACPRICE = this.getACPRICE();
            ACPRICE rhsACPRICE;
            rhsACPRICE = that.getACPRICE();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "acprice", lhsACPRICE), LocatorUtils.property(thatLocator, "acprice", rhsACPRICE), lhsACPRICE, rhsACPRICE)) {
                return false;
            }
        }
        {
            List<AcDefinition> lhsACCOSTS;
            lhsACCOSTS = (((this.accosts!= null)&&(!this.accosts.isEmpty()))?this.getACCOSTS():null);
            List<AcDefinition> rhsACCOSTS;
            rhsACCOSTS = (((that.accosts!= null)&&(!that.accosts.isEmpty()))?that.getACCOSTS():null);
            if (!strategy.equals(LocatorUtils.property(thisLocator, "accosts", lhsACCOSTS), LocatorUtils.property(thatLocator, "accosts", rhsACCOSTS), lhsACCOSTS, rhsACCOSTS)) {
                return false;
            }
        }
        {
            XMLGregorianCalendar lhsDATESTART;
            lhsDATESTART = this.getDATESTART();
            XMLGregorianCalendar rhsDATESTART;
            rhsDATESTART = that.getDATESTART();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "datestart", lhsDATESTART), LocatorUtils.property(thatLocator, "datestart", rhsDATESTART), lhsDATESTART, rhsDATESTART)) {
                return false;
            }
        }
        {
            XMLGregorianCalendar lhsDATEEND;
            lhsDATEEND = this.getDATEEND();
            XMLGregorianCalendar rhsDATEEND;
            rhsDATEEND = that.getDATEEND();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "dateend", lhsDATEEND), LocatorUtils.property(thatLocator, "dateend", rhsDATEEND), lhsDATEEND, rhsDATEEND)) {
                return false;
            }
        }
        {
            Empty lhsINDEFINITEDURATION;
            lhsINDEFINITEDURATION = this.getINDEFINITEDURATION();
            Empty rhsINDEFINITEDURATION;
            rhsINDEFINITEDURATION = that.getINDEFINITEDURATION();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "indefiniteduration", lhsINDEFINITEDURATION), LocatorUtils.property(thatLocator, "indefiniteduration", rhsINDEFINITEDURATION), lhsINDEFINITEDURATION, rhsINDEFINITEDURATION)) {
                return false;
            }
        }
        {
            Empty lhsRENEWAL;
            lhsRENEWAL = this.getRENEWAL();
            Empty rhsRENEWAL;
            rhsRENEWAL = that.getRENEWAL();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "renewal", lhsRENEWAL), LocatorUtils.property(thatLocator, "renewal", rhsRENEWAL), lhsRENEWAL, rhsRENEWAL)) {
                return false;
            }
        }
        {
            TextFtMultiLines lhsRENEWALDESCR;
            lhsRENEWALDESCR = this.getRENEWALDESCR();
            TextFtMultiLines rhsRENEWALDESCR;
            rhsRENEWALDESCR = that.getRENEWALDESCR();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "renewaldescr", lhsRENEWALDESCR), LocatorUtils.property(thatLocator, "renewaldescr", rhsRENEWALDESCR), lhsRENEWALDESCR, rhsRENEWALDESCR)) {
                return false;
            }
        }
        {
            Empty lhsNOEUPROGRRELATED;
            lhsNOEUPROGRRELATED = this.getNOEUPROGRRELATED();
            Empty rhsNOEUPROGRRELATED;
            rhsNOEUPROGRRELATED = that.getNOEUPROGRRELATED();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "noeuprogrrelated", lhsNOEUPROGRRELATED), LocatorUtils.property(thatLocator, "noeuprogrrelated", rhsNOEUPROGRRELATED), lhsNOEUPROGRRELATED, rhsNOEUPROGRRELATED)) {
                return false;
            }
        }
        {
            String lhsEUPROGRRELATED;
            lhsEUPROGRRELATED = this.getEUPROGRRELATED();
            String rhsEUPROGRRELATED;
            rhsEUPROGRRELATED = that.getEUPROGRRELATED();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "euprogrrelated", lhsEUPROGRRELATED), LocatorUtils.property(thatLocator, "euprogrrelated", rhsEUPROGRRELATED), lhsEUPROGRRELATED, rhsEUPROGRRELATED)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = 1;
        {
            List<CpvSet> theCPVADDITIONALS;
            theCPVADDITIONALS = (((this.cpvadditionals!= null)&&(!this.cpvadditionals.isEmpty()))?this.getCPVADDITIONALS():null);
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "cpvadditionals", theCPVADDITIONALS), currentHashCode, theCPVADDITIONALS);
        }
        {
            List<NUTS> theNUTS;
            theNUTS = (((this.nuts!= null)&&(!this.nuts.isEmpty()))?this.getNUTS():null);
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "nuts", theNUTS), currentHashCode, theNUTS);
        }
        {
            TextFtMultiLines theMAINSITE;
            theMAINSITE = this.getMAINSITE();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "mainsite", theMAINSITE), currentHashCode, theMAINSITE);
        }
        {
            TextFtMultiLines theSHORTDESCR;
            theSHORTDESCR = this.getSHORTDESCR();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "shortdescr", theSHORTDESCR), currentHashCode, theSHORTDESCR);
        }
        {
            Empty theACPROCUREMENTDOC;
            theACPROCUREMENTDOC = this.getACPROCUREMENTDOC();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "acprocurementdoc", theACPROCUREMENTDOC), currentHashCode, theACPROCUREMENTDOC);
        }
        {
            List<AcDefinition> theACQUALITIES;
            theACQUALITIES = (((this.acqualities!= null)&&(!this.acqualities.isEmpty()))?this.getACQUALITIES():null);
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "acqualities", theACQUALITIES), currentHashCode, theACQUALITIES);
        }
        {
            ACPRICE theACPRICE;
            theACPRICE = this.getACPRICE();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "acprice", theACPRICE), currentHashCode, theACPRICE);
        }
        {
            List<AcDefinition> theACCOSTS;
            theACCOSTS = (((this.accosts!= null)&&(!this.accosts.isEmpty()))?this.getACCOSTS():null);
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "accosts", theACCOSTS), currentHashCode, theACCOSTS);
        }
        {
            XMLGregorianCalendar theDATESTART;
            theDATESTART = this.getDATESTART();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "datestart", theDATESTART), currentHashCode, theDATESTART);
        }
        {
            XMLGregorianCalendar theDATEEND;
            theDATEEND = this.getDATEEND();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "dateend", theDATEEND), currentHashCode, theDATEEND);
        }
        {
            Empty theINDEFINITEDURATION;
            theINDEFINITEDURATION = this.getINDEFINITEDURATION();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "indefiniteduration", theINDEFINITEDURATION), currentHashCode, theINDEFINITEDURATION);
        }
        {
            Empty theRENEWAL;
            theRENEWAL = this.getRENEWAL();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "renewal", theRENEWAL), currentHashCode, theRENEWAL);
        }
        {
            TextFtMultiLines theRENEWALDESCR;
            theRENEWALDESCR = this.getRENEWALDESCR();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "renewaldescr", theRENEWALDESCR), currentHashCode, theRENEWALDESCR);
        }
        {
            Empty theNOEUPROGRRELATED;
            theNOEUPROGRRELATED = this.getNOEUPROGRRELATED();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "noeuprogrrelated", theNOEUPROGRRELATED), currentHashCode, theNOEUPROGRRELATED);
        }
        {
            String theEUPROGRRELATED;
            theEUPROGRRELATED = this.getEUPROGRRELATED();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "euprogrrelated", theEUPROGRRELATED), currentHashCode, theEUPROGRRELATED);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        {
            List<CpvSet> theCPVADDITIONALS;
            theCPVADDITIONALS = (((this.cpvadditionals!= null)&&(!this.cpvadditionals.isEmpty()))?this.getCPVADDITIONALS():null);
            strategy.appendField(locator, this, "cpvadditionals", buffer, theCPVADDITIONALS);
        }
        {
            List<NUTS> theNUTS;
            theNUTS = (((this.nuts!= null)&&(!this.nuts.isEmpty()))?this.getNUTS():null);
            strategy.appendField(locator, this, "nuts", buffer, theNUTS);
        }
        {
            TextFtMultiLines theMAINSITE;
            theMAINSITE = this.getMAINSITE();
            strategy.appendField(locator, this, "mainsite", buffer, theMAINSITE);
        }
        {
            TextFtMultiLines theSHORTDESCR;
            theSHORTDESCR = this.getSHORTDESCR();
            strategy.appendField(locator, this, "shortdescr", buffer, theSHORTDESCR);
        }
        {
            Empty theACPROCUREMENTDOC;
            theACPROCUREMENTDOC = this.getACPROCUREMENTDOC();
            strategy.appendField(locator, this, "acprocurementdoc", buffer, theACPROCUREMENTDOC);
        }
        {
            List<AcDefinition> theACQUALITIES;
            theACQUALITIES = (((this.acqualities!= null)&&(!this.acqualities.isEmpty()))?this.getACQUALITIES():null);
            strategy.appendField(locator, this, "acqualities", buffer, theACQUALITIES);
        }
        {
            ACPRICE theACPRICE;
            theACPRICE = this.getACPRICE();
            strategy.appendField(locator, this, "acprice", buffer, theACPRICE);
        }
        {
            List<AcDefinition> theACCOSTS;
            theACCOSTS = (((this.accosts!= null)&&(!this.accosts.isEmpty()))?this.getACCOSTS():null);
            strategy.appendField(locator, this, "accosts", buffer, theACCOSTS);
        }
        {
            XMLGregorianCalendar theDATESTART;
            theDATESTART = this.getDATESTART();
            strategy.appendField(locator, this, "datestart", buffer, theDATESTART);
        }
        {
            XMLGregorianCalendar theDATEEND;
            theDATEEND = this.getDATEEND();
            strategy.appendField(locator, this, "dateend", buffer, theDATEEND);
        }
        {
            Empty theINDEFINITEDURATION;
            theINDEFINITEDURATION = this.getINDEFINITEDURATION();
            strategy.appendField(locator, this, "indefiniteduration", buffer, theINDEFINITEDURATION);
        }
        {
            Empty theRENEWAL;
            theRENEWAL = this.getRENEWAL();
            strategy.appendField(locator, this, "renewal", buffer, theRENEWAL);
        }
        {
            TextFtMultiLines theRENEWALDESCR;
            theRENEWALDESCR = this.getRENEWALDESCR();
            strategy.appendField(locator, this, "renewaldescr", buffer, theRENEWALDESCR);
        }
        {
            Empty theNOEUPROGRRELATED;
            theNOEUPROGRRELATED = this.getNOEUPROGRRELATED();
            strategy.appendField(locator, this, "noeuprogrrelated", buffer, theNOEUPROGRRELATED);
        }
        {
            String theEUPROGRRELATED;
            theEUPROGRRELATED = this.getEUPROGRRELATED();
            strategy.appendField(locator, this, "euprogrrelated", buffer, theEUPROGRRELATED);
        }
        return buffer;
    }

}
