//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.04 at 01:40:50 PM MEZ 
//


package eu.europa.publications.formex.ted.schema;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.datatype.XMLGregorianCalendar;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * Section IV: PROCEDURE
 * 
 * <p>Java class for procedure_f05 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="procedure_f05">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element ref="{http://formex.publications.europa.eu/ted/schema/reception/R2.0.9.S01}PT_OPEN"/>
 *           &lt;element ref="{http://formex.publications.europa.eu/ted/schema/reception/R2.0.9.S01}PT_RESTRICTED"/>
 *           &lt;element ref="{http://formex.publications.europa.eu/ted/schema/reception/R2.0.9.S01}PT_NEGOTIATED_WITH_PRIOR_CALL"/>
 *           &lt;element ref="{http://formex.publications.europa.eu/ted/schema/reception/R2.0.9.S01}PT_COMPETITIVE_DIALOGUE"/>
 *           &lt;element ref="{http://formex.publications.europa.eu/ted/schema/reception/R2.0.9.S01}PT_INNOVATION_PARTNERSHIP"/>
 *         &lt;/choice>
 *         &lt;element name="FRAMEWORK" type="{http://formex.publications.europa.eu/ted/schema/reception/R2.0.9.S01}framework_info" minOccurs="0"/>
 *         &lt;group ref="{http://formex.publications.europa.eu/ted/schema/reception/R2.0.9.S01}dps_purchasers" minOccurs="0"/>
 *         &lt;element ref="{http://formex.publications.europa.eu/ted/schema/reception/R2.0.9.S01}REDUCTION_RECOURSE" minOccurs="0"/>
 *         &lt;group ref="{http://formex.publications.europa.eu/ted/schema/reception/R2.0.9.S01}eauction" minOccurs="0"/>
 *         &lt;group ref="{http://formex.publications.europa.eu/ted/schema/reception/R2.0.9.S01}gpa"/>
 *         &lt;element ref="{http://formex.publications.europa.eu/ted/schema/reception/R2.0.9.S01}NOTICE_NUMBER_OJ" minOccurs="0"/>
 *         &lt;group ref="{http://formex.publications.europa.eu/ted/schema/reception/R2.0.9.S01}receipt_tenders"/>
 *         &lt;element ref="{http://formex.publications.europa.eu/ted/schema/reception/R2.0.9.S01}DATE_DISPATCH_INVITATIONS" minOccurs="0"/>
 *         &lt;element ref="{http://formex.publications.europa.eu/ted/schema/reception/R2.0.9.S01}LANGUAGES"/>
 *         &lt;group ref="{http://formex.publications.europa.eu/ted/schema/reception/R2.0.9.S01}time_frame_tender_valid" minOccurs="0"/>
 *         &lt;element ref="{http://formex.publications.europa.eu/ted/schema/reception/R2.0.9.S01}OPENING_CONDITION" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "procedure_f05", propOrder = {
    "ptinnovationpartnership",
    "ptcompetitivedialogue",
    "ptnegotiatedwithpriorcall",
    "ptrestricted",
    "ptopen",
    "framework",
    "dps",
    "dpsadditionalpurchasers",
    "reductionrecourse",
    "eauctionused",
    "infoaddeauction",
    "nocontractcoveredgpa",
    "contractcoveredgpa",
    "noticenumberoj",
    "datereceipttenders",
    "timereceipttenders",
    "datedispatchinvitations",
    "languages",
    "durationtendervalid",
    "datetendervalid",
    "openingcondition"
})
public class ProcedureF05
    implements Equals, HashCode, ToString
{

    @XmlElement(name = "PT_INNOVATION_PARTNERSHIP")
    protected Empty ptinnovationpartnership;
    @XmlElement(name = "PT_COMPETITIVE_DIALOGUE")
    protected Empty ptcompetitivedialogue;
    @XmlElement(name = "PT_NEGOTIATED_WITH_PRIOR_CALL")
    protected Empty ptnegotiatedwithpriorcall;
    @XmlElement(name = "PT_RESTRICTED")
    protected Empty ptrestricted;
    @XmlElement(name = "PT_OPEN")
    protected Empty ptopen;
    @XmlElement(name = "FRAMEWORK")
    protected FrameworkInfo framework;
    @XmlElement(name = "DPS")
    protected Empty dps;
    @XmlElement(name = "DPS_ADDITIONAL_PURCHASERS")
    protected Empty dpsadditionalpurchasers;
    @XmlElement(name = "REDUCTION_RECOURSE")
    protected Empty reductionrecourse;
    @XmlElement(name = "EAUCTION_USED")
    protected Empty eauctionused;
    @XmlElement(name = "INFO_ADD_EAUCTION")
    protected TextFtMultiLines infoaddeauction;
    @XmlElement(name = "NO_CONTRACT_COVERED_GPA")
    protected Empty nocontractcoveredgpa;
    @XmlElement(name = "CONTRACT_COVERED_GPA")
    protected Empty contractcoveredgpa;
    @XmlElement(name = "NOTICE_NUMBER_OJ")
    protected String noticenumberoj;
    @XmlElement(name = "DATE_RECEIPT_TENDERS", required = true)
    protected XMLGregorianCalendar datereceipttenders;
    @XmlElement(name = "TIME_RECEIPT_TENDERS")
    protected String timereceipttenders;
    @XmlElement(name = "DATE_DISPATCH_INVITATIONS")
    protected XMLGregorianCalendar datedispatchinvitations;
    @XmlElement(name = "LANGUAGES", required = true)
    protected LANGUAGES languages;
    @XmlElement(name = "DURATION_TENDER_VALID")
    protected ProcedureF05 .DURATIONTENDERVALID durationtendervalid;
    @XmlElement(name = "DATE_TENDER_VALID")
    protected XMLGregorianCalendar datetendervalid;
    @XmlElement(name = "OPENING_CONDITION")
    protected OPENINGCONDITION openingcondition;

    /**
     * Gets the value of the ptinnovationpartnership property.
     * 
     * @return
     *     possible object is
     *     {@link Empty }
     *     
     */
    public Empty getPTINNOVATIONPARTNERSHIP() {
        return ptinnovationpartnership;
    }

    /**
     * Sets the value of the ptinnovationpartnership property.
     * 
     * @param value
     *     allowed object is
     *     {@link Empty }
     *     
     */
    public void setPTINNOVATIONPARTNERSHIP(Empty value) {
        this.ptinnovationpartnership = value;
    }

    /**
     * Gets the value of the ptcompetitivedialogue property.
     * 
     * @return
     *     possible object is
     *     {@link Empty }
     *     
     */
    public Empty getPTCOMPETITIVEDIALOGUE() {
        return ptcompetitivedialogue;
    }

    /**
     * Sets the value of the ptcompetitivedialogue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Empty }
     *     
     */
    public void setPTCOMPETITIVEDIALOGUE(Empty value) {
        this.ptcompetitivedialogue = value;
    }

    /**
     * Gets the value of the ptnegotiatedwithpriorcall property.
     * 
     * @return
     *     possible object is
     *     {@link Empty }
     *     
     */
    public Empty getPTNEGOTIATEDWITHPRIORCALL() {
        return ptnegotiatedwithpriorcall;
    }

    /**
     * Sets the value of the ptnegotiatedwithpriorcall property.
     * 
     * @param value
     *     allowed object is
     *     {@link Empty }
     *     
     */
    public void setPTNEGOTIATEDWITHPRIORCALL(Empty value) {
        this.ptnegotiatedwithpriorcall = value;
    }

    /**
     * Gets the value of the ptrestricted property.
     * 
     * @return
     *     possible object is
     *     {@link Empty }
     *     
     */
    public Empty getPTRESTRICTED() {
        return ptrestricted;
    }

    /**
     * Sets the value of the ptrestricted property.
     * 
     * @param value
     *     allowed object is
     *     {@link Empty }
     *     
     */
    public void setPTRESTRICTED(Empty value) {
        this.ptrestricted = value;
    }

    /**
     * Gets the value of the ptopen property.
     * 
     * @return
     *     possible object is
     *     {@link Empty }
     *     
     */
    public Empty getPTOPEN() {
        return ptopen;
    }

    /**
     * Sets the value of the ptopen property.
     * 
     * @param value
     *     allowed object is
     *     {@link Empty }
     *     
     */
    public void setPTOPEN(Empty value) {
        this.ptopen = value;
    }

    /**
     * Gets the value of the framework property.
     * 
     * @return
     *     possible object is
     *     {@link FrameworkInfo }
     *     
     */
    public FrameworkInfo getFRAMEWORK() {
        return framework;
    }

    /**
     * Sets the value of the framework property.
     * 
     * @param value
     *     allowed object is
     *     {@link FrameworkInfo }
     *     
     */
    public void setFRAMEWORK(FrameworkInfo value) {
        this.framework = value;
    }

    /**
     * Gets the value of the dps property.
     * 
     * @return
     *     possible object is
     *     {@link Empty }
     *     
     */
    public Empty getDPS() {
        return dps;
    }

    /**
     * Sets the value of the dps property.
     * 
     * @param value
     *     allowed object is
     *     {@link Empty }
     *     
     */
    public void setDPS(Empty value) {
        this.dps = value;
    }

    /**
     * Gets the value of the dpsadditionalpurchasers property.
     * 
     * @return
     *     possible object is
     *     {@link Empty }
     *     
     */
    public Empty getDPSADDITIONALPURCHASERS() {
        return dpsadditionalpurchasers;
    }

    /**
     * Sets the value of the dpsadditionalpurchasers property.
     * 
     * @param value
     *     allowed object is
     *     {@link Empty }
     *     
     */
    public void setDPSADDITIONALPURCHASERS(Empty value) {
        this.dpsadditionalpurchasers = value;
    }

    /**
     * Gets the value of the reductionrecourse property.
     * 
     * @return
     *     possible object is
     *     {@link Empty }
     *     
     */
    public Empty getREDUCTIONRECOURSE() {
        return reductionrecourse;
    }

    /**
     * Sets the value of the reductionrecourse property.
     * 
     * @param value
     *     allowed object is
     *     {@link Empty }
     *     
     */
    public void setREDUCTIONRECOURSE(Empty value) {
        this.reductionrecourse = value;
    }

    /**
     * Gets the value of the eauctionused property.
     * 
     * @return
     *     possible object is
     *     {@link Empty }
     *     
     */
    public Empty getEAUCTIONUSED() {
        return eauctionused;
    }

    /**
     * Sets the value of the eauctionused property.
     * 
     * @param value
     *     allowed object is
     *     {@link Empty }
     *     
     */
    public void setEAUCTIONUSED(Empty value) {
        this.eauctionused = value;
    }

    /**
     * Gets the value of the infoaddeauction property.
     * 
     * @return
     *     possible object is
     *     {@link TextFtMultiLines }
     *     
     */
    public TextFtMultiLines getINFOADDEAUCTION() {
        return infoaddeauction;
    }

    /**
     * Sets the value of the infoaddeauction property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextFtMultiLines }
     *     
     */
    public void setINFOADDEAUCTION(TextFtMultiLines value) {
        this.infoaddeauction = value;
    }

    /**
     * Gets the value of the nocontractcoveredgpa property.
     * 
     * @return
     *     possible object is
     *     {@link Empty }
     *     
     */
    public Empty getNOCONTRACTCOVEREDGPA() {
        return nocontractcoveredgpa;
    }

    /**
     * Sets the value of the nocontractcoveredgpa property.
     * 
     * @param value
     *     allowed object is
     *     {@link Empty }
     *     
     */
    public void setNOCONTRACTCOVEREDGPA(Empty value) {
        this.nocontractcoveredgpa = value;
    }

    /**
     * Gets the value of the contractcoveredgpa property.
     * 
     * @return
     *     possible object is
     *     {@link Empty }
     *     
     */
    public Empty getCONTRACTCOVEREDGPA() {
        return contractcoveredgpa;
    }

    /**
     * Sets the value of the contractcoveredgpa property.
     * 
     * @param value
     *     allowed object is
     *     {@link Empty }
     *     
     */
    public void setCONTRACTCOVEREDGPA(Empty value) {
        this.contractcoveredgpa = value;
    }

    /**
     * Gets the value of the noticenumberoj property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNOTICENUMBEROJ() {
        return noticenumberoj;
    }

    /**
     * Sets the value of the noticenumberoj property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNOTICENUMBEROJ(String value) {
        this.noticenumberoj = value;
    }

    /**
     * Gets the value of the datereceipttenders property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDATERECEIPTTENDERS() {
        return datereceipttenders;
    }

    /**
     * Sets the value of the datereceipttenders property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDATERECEIPTTENDERS(XMLGregorianCalendar value) {
        this.datereceipttenders = value;
    }

    /**
     * Gets the value of the timereceipttenders property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTIMERECEIPTTENDERS() {
        return timereceipttenders;
    }

    /**
     * Sets the value of the timereceipttenders property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTIMERECEIPTTENDERS(String value) {
        this.timereceipttenders = value;
    }

    /**
     * Gets the value of the datedispatchinvitations property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDATEDISPATCHINVITATIONS() {
        return datedispatchinvitations;
    }

    /**
     * Sets the value of the datedispatchinvitations property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDATEDISPATCHINVITATIONS(XMLGregorianCalendar value) {
        this.datedispatchinvitations = value;
    }

    /**
     * Gets the value of the languages property.
     * 
     * @return
     *     possible object is
     *     {@link LANGUAGES }
     *     
     */
    public LANGUAGES getLANGUAGES() {
        return languages;
    }

    /**
     * Sets the value of the languages property.
     * 
     * @param value
     *     allowed object is
     *     {@link LANGUAGES }
     *     
     */
    public void setLANGUAGES(LANGUAGES value) {
        this.languages = value;
    }

    /**
     * Gets the value of the durationtendervalid property.
     * 
     * @return
     *     possible object is
     *     {@link ProcedureF05 .DURATIONTENDERVALID }
     *     
     */
    public ProcedureF05 .DURATIONTENDERVALID getDURATIONTENDERVALID() {
        return durationtendervalid;
    }

    /**
     * Sets the value of the durationtendervalid property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProcedureF05 .DURATIONTENDERVALID }
     *     
     */
    public void setDURATIONTENDERVALID(ProcedureF05 .DURATIONTENDERVALID value) {
        this.durationtendervalid = value;
    }

    /**
     * Gets the value of the datetendervalid property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDATETENDERVALID() {
        return datetendervalid;
    }

    /**
     * Sets the value of the datetendervalid property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDATETENDERVALID(XMLGregorianCalendar value) {
        this.datetendervalid = value;
    }

    /**
     * Gets the value of the openingcondition property.
     * 
     * @return
     *     possible object is
     *     {@link OPENINGCONDITION }
     *     
     */
    public OPENINGCONDITION getOPENINGCONDITION() {
        return openingcondition;
    }

    /**
     * Sets the value of the openingcondition property.
     * 
     * @param value
     *     allowed object is
     *     {@link OPENINGCONDITION }
     *     
     */
    public void setOPENINGCONDITION(OPENINGCONDITION value) {
        this.openingcondition = value;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof ProcedureF05)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final ProcedureF05 that = ((ProcedureF05) object);
        {
            Empty lhsPTINNOVATIONPARTNERSHIP;
            lhsPTINNOVATIONPARTNERSHIP = this.getPTINNOVATIONPARTNERSHIP();
            Empty rhsPTINNOVATIONPARTNERSHIP;
            rhsPTINNOVATIONPARTNERSHIP = that.getPTINNOVATIONPARTNERSHIP();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "ptinnovationpartnership", lhsPTINNOVATIONPARTNERSHIP), LocatorUtils.property(thatLocator, "ptinnovationpartnership", rhsPTINNOVATIONPARTNERSHIP), lhsPTINNOVATIONPARTNERSHIP, rhsPTINNOVATIONPARTNERSHIP)) {
                return false;
            }
        }
        {
            Empty lhsPTCOMPETITIVEDIALOGUE;
            lhsPTCOMPETITIVEDIALOGUE = this.getPTCOMPETITIVEDIALOGUE();
            Empty rhsPTCOMPETITIVEDIALOGUE;
            rhsPTCOMPETITIVEDIALOGUE = that.getPTCOMPETITIVEDIALOGUE();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "ptcompetitivedialogue", lhsPTCOMPETITIVEDIALOGUE), LocatorUtils.property(thatLocator, "ptcompetitivedialogue", rhsPTCOMPETITIVEDIALOGUE), lhsPTCOMPETITIVEDIALOGUE, rhsPTCOMPETITIVEDIALOGUE)) {
                return false;
            }
        }
        {
            Empty lhsPTNEGOTIATEDWITHPRIORCALL;
            lhsPTNEGOTIATEDWITHPRIORCALL = this.getPTNEGOTIATEDWITHPRIORCALL();
            Empty rhsPTNEGOTIATEDWITHPRIORCALL;
            rhsPTNEGOTIATEDWITHPRIORCALL = that.getPTNEGOTIATEDWITHPRIORCALL();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "ptnegotiatedwithpriorcall", lhsPTNEGOTIATEDWITHPRIORCALL), LocatorUtils.property(thatLocator, "ptnegotiatedwithpriorcall", rhsPTNEGOTIATEDWITHPRIORCALL), lhsPTNEGOTIATEDWITHPRIORCALL, rhsPTNEGOTIATEDWITHPRIORCALL)) {
                return false;
            }
        }
        {
            Empty lhsPTRESTRICTED;
            lhsPTRESTRICTED = this.getPTRESTRICTED();
            Empty rhsPTRESTRICTED;
            rhsPTRESTRICTED = that.getPTRESTRICTED();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "ptrestricted", lhsPTRESTRICTED), LocatorUtils.property(thatLocator, "ptrestricted", rhsPTRESTRICTED), lhsPTRESTRICTED, rhsPTRESTRICTED)) {
                return false;
            }
        }
        {
            Empty lhsPTOPEN;
            lhsPTOPEN = this.getPTOPEN();
            Empty rhsPTOPEN;
            rhsPTOPEN = that.getPTOPEN();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "ptopen", lhsPTOPEN), LocatorUtils.property(thatLocator, "ptopen", rhsPTOPEN), lhsPTOPEN, rhsPTOPEN)) {
                return false;
            }
        }
        {
            FrameworkInfo lhsFRAMEWORK;
            lhsFRAMEWORK = this.getFRAMEWORK();
            FrameworkInfo rhsFRAMEWORK;
            rhsFRAMEWORK = that.getFRAMEWORK();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "framework", lhsFRAMEWORK), LocatorUtils.property(thatLocator, "framework", rhsFRAMEWORK), lhsFRAMEWORK, rhsFRAMEWORK)) {
                return false;
            }
        }
        {
            Empty lhsDPS;
            lhsDPS = this.getDPS();
            Empty rhsDPS;
            rhsDPS = that.getDPS();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "dps", lhsDPS), LocatorUtils.property(thatLocator, "dps", rhsDPS), lhsDPS, rhsDPS)) {
                return false;
            }
        }
        {
            Empty lhsDPSADDITIONALPURCHASERS;
            lhsDPSADDITIONALPURCHASERS = this.getDPSADDITIONALPURCHASERS();
            Empty rhsDPSADDITIONALPURCHASERS;
            rhsDPSADDITIONALPURCHASERS = that.getDPSADDITIONALPURCHASERS();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "dpsadditionalpurchasers", lhsDPSADDITIONALPURCHASERS), LocatorUtils.property(thatLocator, "dpsadditionalpurchasers", rhsDPSADDITIONALPURCHASERS), lhsDPSADDITIONALPURCHASERS, rhsDPSADDITIONALPURCHASERS)) {
                return false;
            }
        }
        {
            Empty lhsREDUCTIONRECOURSE;
            lhsREDUCTIONRECOURSE = this.getREDUCTIONRECOURSE();
            Empty rhsREDUCTIONRECOURSE;
            rhsREDUCTIONRECOURSE = that.getREDUCTIONRECOURSE();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "reductionrecourse", lhsREDUCTIONRECOURSE), LocatorUtils.property(thatLocator, "reductionrecourse", rhsREDUCTIONRECOURSE), lhsREDUCTIONRECOURSE, rhsREDUCTIONRECOURSE)) {
                return false;
            }
        }
        {
            Empty lhsEAUCTIONUSED;
            lhsEAUCTIONUSED = this.getEAUCTIONUSED();
            Empty rhsEAUCTIONUSED;
            rhsEAUCTIONUSED = that.getEAUCTIONUSED();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "eauctionused", lhsEAUCTIONUSED), LocatorUtils.property(thatLocator, "eauctionused", rhsEAUCTIONUSED), lhsEAUCTIONUSED, rhsEAUCTIONUSED)) {
                return false;
            }
        }
        {
            TextFtMultiLines lhsINFOADDEAUCTION;
            lhsINFOADDEAUCTION = this.getINFOADDEAUCTION();
            TextFtMultiLines rhsINFOADDEAUCTION;
            rhsINFOADDEAUCTION = that.getINFOADDEAUCTION();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "infoaddeauction", lhsINFOADDEAUCTION), LocatorUtils.property(thatLocator, "infoaddeauction", rhsINFOADDEAUCTION), lhsINFOADDEAUCTION, rhsINFOADDEAUCTION)) {
                return false;
            }
        }
        {
            Empty lhsNOCONTRACTCOVEREDGPA;
            lhsNOCONTRACTCOVEREDGPA = this.getNOCONTRACTCOVEREDGPA();
            Empty rhsNOCONTRACTCOVEREDGPA;
            rhsNOCONTRACTCOVEREDGPA = that.getNOCONTRACTCOVEREDGPA();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "nocontractcoveredgpa", lhsNOCONTRACTCOVEREDGPA), LocatorUtils.property(thatLocator, "nocontractcoveredgpa", rhsNOCONTRACTCOVEREDGPA), lhsNOCONTRACTCOVEREDGPA, rhsNOCONTRACTCOVEREDGPA)) {
                return false;
            }
        }
        {
            Empty lhsCONTRACTCOVEREDGPA;
            lhsCONTRACTCOVEREDGPA = this.getCONTRACTCOVEREDGPA();
            Empty rhsCONTRACTCOVEREDGPA;
            rhsCONTRACTCOVEREDGPA = that.getCONTRACTCOVEREDGPA();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "contractcoveredgpa", lhsCONTRACTCOVEREDGPA), LocatorUtils.property(thatLocator, "contractcoveredgpa", rhsCONTRACTCOVEREDGPA), lhsCONTRACTCOVEREDGPA, rhsCONTRACTCOVEREDGPA)) {
                return false;
            }
        }
        {
            String lhsNOTICENUMBEROJ;
            lhsNOTICENUMBEROJ = this.getNOTICENUMBEROJ();
            String rhsNOTICENUMBEROJ;
            rhsNOTICENUMBEROJ = that.getNOTICENUMBEROJ();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "noticenumberoj", lhsNOTICENUMBEROJ), LocatorUtils.property(thatLocator, "noticenumberoj", rhsNOTICENUMBEROJ), lhsNOTICENUMBEROJ, rhsNOTICENUMBEROJ)) {
                return false;
            }
        }
        {
            XMLGregorianCalendar lhsDATERECEIPTTENDERS;
            lhsDATERECEIPTTENDERS = this.getDATERECEIPTTENDERS();
            XMLGregorianCalendar rhsDATERECEIPTTENDERS;
            rhsDATERECEIPTTENDERS = that.getDATERECEIPTTENDERS();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "datereceipttenders", lhsDATERECEIPTTENDERS), LocatorUtils.property(thatLocator, "datereceipttenders", rhsDATERECEIPTTENDERS), lhsDATERECEIPTTENDERS, rhsDATERECEIPTTENDERS)) {
                return false;
            }
        }
        {
            String lhsTIMERECEIPTTENDERS;
            lhsTIMERECEIPTTENDERS = this.getTIMERECEIPTTENDERS();
            String rhsTIMERECEIPTTENDERS;
            rhsTIMERECEIPTTENDERS = that.getTIMERECEIPTTENDERS();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "timereceipttenders", lhsTIMERECEIPTTENDERS), LocatorUtils.property(thatLocator, "timereceipttenders", rhsTIMERECEIPTTENDERS), lhsTIMERECEIPTTENDERS, rhsTIMERECEIPTTENDERS)) {
                return false;
            }
        }
        {
            XMLGregorianCalendar lhsDATEDISPATCHINVITATIONS;
            lhsDATEDISPATCHINVITATIONS = this.getDATEDISPATCHINVITATIONS();
            XMLGregorianCalendar rhsDATEDISPATCHINVITATIONS;
            rhsDATEDISPATCHINVITATIONS = that.getDATEDISPATCHINVITATIONS();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "datedispatchinvitations", lhsDATEDISPATCHINVITATIONS), LocatorUtils.property(thatLocator, "datedispatchinvitations", rhsDATEDISPATCHINVITATIONS), lhsDATEDISPATCHINVITATIONS, rhsDATEDISPATCHINVITATIONS)) {
                return false;
            }
        }
        {
            LANGUAGES lhsLANGUAGES;
            lhsLANGUAGES = this.getLANGUAGES();
            LANGUAGES rhsLANGUAGES;
            rhsLANGUAGES = that.getLANGUAGES();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "languages", lhsLANGUAGES), LocatorUtils.property(thatLocator, "languages", rhsLANGUAGES), lhsLANGUAGES, rhsLANGUAGES)) {
                return false;
            }
        }
        {
            ProcedureF05 .DURATIONTENDERVALID lhsDURATIONTENDERVALID;
            lhsDURATIONTENDERVALID = this.getDURATIONTENDERVALID();
            ProcedureF05 .DURATIONTENDERVALID rhsDURATIONTENDERVALID;
            rhsDURATIONTENDERVALID = that.getDURATIONTENDERVALID();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "durationtendervalid", lhsDURATIONTENDERVALID), LocatorUtils.property(thatLocator, "durationtendervalid", rhsDURATIONTENDERVALID), lhsDURATIONTENDERVALID, rhsDURATIONTENDERVALID)) {
                return false;
            }
        }
        {
            XMLGregorianCalendar lhsDATETENDERVALID;
            lhsDATETENDERVALID = this.getDATETENDERVALID();
            XMLGregorianCalendar rhsDATETENDERVALID;
            rhsDATETENDERVALID = that.getDATETENDERVALID();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "datetendervalid", lhsDATETENDERVALID), LocatorUtils.property(thatLocator, "datetendervalid", rhsDATETENDERVALID), lhsDATETENDERVALID, rhsDATETENDERVALID)) {
                return false;
            }
        }
        {
            OPENINGCONDITION lhsOPENINGCONDITION;
            lhsOPENINGCONDITION = this.getOPENINGCONDITION();
            OPENINGCONDITION rhsOPENINGCONDITION;
            rhsOPENINGCONDITION = that.getOPENINGCONDITION();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "openingcondition", lhsOPENINGCONDITION), LocatorUtils.property(thatLocator, "openingcondition", rhsOPENINGCONDITION), lhsOPENINGCONDITION, rhsOPENINGCONDITION)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = 1;
        {
            Empty thePTINNOVATIONPARTNERSHIP;
            thePTINNOVATIONPARTNERSHIP = this.getPTINNOVATIONPARTNERSHIP();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "ptinnovationpartnership", thePTINNOVATIONPARTNERSHIP), currentHashCode, thePTINNOVATIONPARTNERSHIP);
        }
        {
            Empty thePTCOMPETITIVEDIALOGUE;
            thePTCOMPETITIVEDIALOGUE = this.getPTCOMPETITIVEDIALOGUE();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "ptcompetitivedialogue", thePTCOMPETITIVEDIALOGUE), currentHashCode, thePTCOMPETITIVEDIALOGUE);
        }
        {
            Empty thePTNEGOTIATEDWITHPRIORCALL;
            thePTNEGOTIATEDWITHPRIORCALL = this.getPTNEGOTIATEDWITHPRIORCALL();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "ptnegotiatedwithpriorcall", thePTNEGOTIATEDWITHPRIORCALL), currentHashCode, thePTNEGOTIATEDWITHPRIORCALL);
        }
        {
            Empty thePTRESTRICTED;
            thePTRESTRICTED = this.getPTRESTRICTED();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "ptrestricted", thePTRESTRICTED), currentHashCode, thePTRESTRICTED);
        }
        {
            Empty thePTOPEN;
            thePTOPEN = this.getPTOPEN();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "ptopen", thePTOPEN), currentHashCode, thePTOPEN);
        }
        {
            FrameworkInfo theFRAMEWORK;
            theFRAMEWORK = this.getFRAMEWORK();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "framework", theFRAMEWORK), currentHashCode, theFRAMEWORK);
        }
        {
            Empty theDPS;
            theDPS = this.getDPS();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "dps", theDPS), currentHashCode, theDPS);
        }
        {
            Empty theDPSADDITIONALPURCHASERS;
            theDPSADDITIONALPURCHASERS = this.getDPSADDITIONALPURCHASERS();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "dpsadditionalpurchasers", theDPSADDITIONALPURCHASERS), currentHashCode, theDPSADDITIONALPURCHASERS);
        }
        {
            Empty theREDUCTIONRECOURSE;
            theREDUCTIONRECOURSE = this.getREDUCTIONRECOURSE();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "reductionrecourse", theREDUCTIONRECOURSE), currentHashCode, theREDUCTIONRECOURSE);
        }
        {
            Empty theEAUCTIONUSED;
            theEAUCTIONUSED = this.getEAUCTIONUSED();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "eauctionused", theEAUCTIONUSED), currentHashCode, theEAUCTIONUSED);
        }
        {
            TextFtMultiLines theINFOADDEAUCTION;
            theINFOADDEAUCTION = this.getINFOADDEAUCTION();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "infoaddeauction", theINFOADDEAUCTION), currentHashCode, theINFOADDEAUCTION);
        }
        {
            Empty theNOCONTRACTCOVEREDGPA;
            theNOCONTRACTCOVEREDGPA = this.getNOCONTRACTCOVEREDGPA();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "nocontractcoveredgpa", theNOCONTRACTCOVEREDGPA), currentHashCode, theNOCONTRACTCOVEREDGPA);
        }
        {
            Empty theCONTRACTCOVEREDGPA;
            theCONTRACTCOVEREDGPA = this.getCONTRACTCOVEREDGPA();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "contractcoveredgpa", theCONTRACTCOVEREDGPA), currentHashCode, theCONTRACTCOVEREDGPA);
        }
        {
            String theNOTICENUMBEROJ;
            theNOTICENUMBEROJ = this.getNOTICENUMBEROJ();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "noticenumberoj", theNOTICENUMBEROJ), currentHashCode, theNOTICENUMBEROJ);
        }
        {
            XMLGregorianCalendar theDATERECEIPTTENDERS;
            theDATERECEIPTTENDERS = this.getDATERECEIPTTENDERS();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "datereceipttenders", theDATERECEIPTTENDERS), currentHashCode, theDATERECEIPTTENDERS);
        }
        {
            String theTIMERECEIPTTENDERS;
            theTIMERECEIPTTENDERS = this.getTIMERECEIPTTENDERS();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "timereceipttenders", theTIMERECEIPTTENDERS), currentHashCode, theTIMERECEIPTTENDERS);
        }
        {
            XMLGregorianCalendar theDATEDISPATCHINVITATIONS;
            theDATEDISPATCHINVITATIONS = this.getDATEDISPATCHINVITATIONS();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "datedispatchinvitations", theDATEDISPATCHINVITATIONS), currentHashCode, theDATEDISPATCHINVITATIONS);
        }
        {
            LANGUAGES theLANGUAGES;
            theLANGUAGES = this.getLANGUAGES();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "languages", theLANGUAGES), currentHashCode, theLANGUAGES);
        }
        {
            ProcedureF05 .DURATIONTENDERVALID theDURATIONTENDERVALID;
            theDURATIONTENDERVALID = this.getDURATIONTENDERVALID();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "durationtendervalid", theDURATIONTENDERVALID), currentHashCode, theDURATIONTENDERVALID);
        }
        {
            XMLGregorianCalendar theDATETENDERVALID;
            theDATETENDERVALID = this.getDATETENDERVALID();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "datetendervalid", theDATETENDERVALID), currentHashCode, theDATETENDERVALID);
        }
        {
            OPENINGCONDITION theOPENINGCONDITION;
            theOPENINGCONDITION = this.getOPENINGCONDITION();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "openingcondition", theOPENINGCONDITION), currentHashCode, theOPENINGCONDITION);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        {
            Empty thePTINNOVATIONPARTNERSHIP;
            thePTINNOVATIONPARTNERSHIP = this.getPTINNOVATIONPARTNERSHIP();
            strategy.appendField(locator, this, "ptinnovationpartnership", buffer, thePTINNOVATIONPARTNERSHIP);
        }
        {
            Empty thePTCOMPETITIVEDIALOGUE;
            thePTCOMPETITIVEDIALOGUE = this.getPTCOMPETITIVEDIALOGUE();
            strategy.appendField(locator, this, "ptcompetitivedialogue", buffer, thePTCOMPETITIVEDIALOGUE);
        }
        {
            Empty thePTNEGOTIATEDWITHPRIORCALL;
            thePTNEGOTIATEDWITHPRIORCALL = this.getPTNEGOTIATEDWITHPRIORCALL();
            strategy.appendField(locator, this, "ptnegotiatedwithpriorcall", buffer, thePTNEGOTIATEDWITHPRIORCALL);
        }
        {
            Empty thePTRESTRICTED;
            thePTRESTRICTED = this.getPTRESTRICTED();
            strategy.appendField(locator, this, "ptrestricted", buffer, thePTRESTRICTED);
        }
        {
            Empty thePTOPEN;
            thePTOPEN = this.getPTOPEN();
            strategy.appendField(locator, this, "ptopen", buffer, thePTOPEN);
        }
        {
            FrameworkInfo theFRAMEWORK;
            theFRAMEWORK = this.getFRAMEWORK();
            strategy.appendField(locator, this, "framework", buffer, theFRAMEWORK);
        }
        {
            Empty theDPS;
            theDPS = this.getDPS();
            strategy.appendField(locator, this, "dps", buffer, theDPS);
        }
        {
            Empty theDPSADDITIONALPURCHASERS;
            theDPSADDITIONALPURCHASERS = this.getDPSADDITIONALPURCHASERS();
            strategy.appendField(locator, this, "dpsadditionalpurchasers", buffer, theDPSADDITIONALPURCHASERS);
        }
        {
            Empty theREDUCTIONRECOURSE;
            theREDUCTIONRECOURSE = this.getREDUCTIONRECOURSE();
            strategy.appendField(locator, this, "reductionrecourse", buffer, theREDUCTIONRECOURSE);
        }
        {
            Empty theEAUCTIONUSED;
            theEAUCTIONUSED = this.getEAUCTIONUSED();
            strategy.appendField(locator, this, "eauctionused", buffer, theEAUCTIONUSED);
        }
        {
            TextFtMultiLines theINFOADDEAUCTION;
            theINFOADDEAUCTION = this.getINFOADDEAUCTION();
            strategy.appendField(locator, this, "infoaddeauction", buffer, theINFOADDEAUCTION);
        }
        {
            Empty theNOCONTRACTCOVEREDGPA;
            theNOCONTRACTCOVEREDGPA = this.getNOCONTRACTCOVEREDGPA();
            strategy.appendField(locator, this, "nocontractcoveredgpa", buffer, theNOCONTRACTCOVEREDGPA);
        }
        {
            Empty theCONTRACTCOVEREDGPA;
            theCONTRACTCOVEREDGPA = this.getCONTRACTCOVEREDGPA();
            strategy.appendField(locator, this, "contractcoveredgpa", buffer, theCONTRACTCOVEREDGPA);
        }
        {
            String theNOTICENUMBEROJ;
            theNOTICENUMBEROJ = this.getNOTICENUMBEROJ();
            strategy.appendField(locator, this, "noticenumberoj", buffer, theNOTICENUMBEROJ);
        }
        {
            XMLGregorianCalendar theDATERECEIPTTENDERS;
            theDATERECEIPTTENDERS = this.getDATERECEIPTTENDERS();
            strategy.appendField(locator, this, "datereceipttenders", buffer, theDATERECEIPTTENDERS);
        }
        {
            String theTIMERECEIPTTENDERS;
            theTIMERECEIPTTENDERS = this.getTIMERECEIPTTENDERS();
            strategy.appendField(locator, this, "timereceipttenders", buffer, theTIMERECEIPTTENDERS);
        }
        {
            XMLGregorianCalendar theDATEDISPATCHINVITATIONS;
            theDATEDISPATCHINVITATIONS = this.getDATEDISPATCHINVITATIONS();
            strategy.appendField(locator, this, "datedispatchinvitations", buffer, theDATEDISPATCHINVITATIONS);
        }
        {
            LANGUAGES theLANGUAGES;
            theLANGUAGES = this.getLANGUAGES();
            strategy.appendField(locator, this, "languages", buffer, theLANGUAGES);
        }
        {
            ProcedureF05 .DURATIONTENDERVALID theDURATIONTENDERVALID;
            theDURATIONTENDERVALID = this.getDURATIONTENDERVALID();
            strategy.appendField(locator, this, "durationtendervalid", buffer, theDURATIONTENDERVALID);
        }
        {
            XMLGregorianCalendar theDATETENDERVALID;
            theDATETENDERVALID = this.getDATETENDERVALID();
            strategy.appendField(locator, this, "datetendervalid", buffer, theDATETENDERVALID);
        }
        {
            OPENINGCONDITION theOPENINGCONDITION;
            theOPENINGCONDITION = this.getOPENINGCONDITION();
            strategy.appendField(locator, this, "openingcondition", buffer, theOPENINGCONDITION);
        }
        return buffer;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://formex.publications.europa.eu/ted/schema/reception/R2.0.9.S01>duration_value_3d">
     *       &lt;attribute name="TYPE" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" fixed="MONTH" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class DURATIONTENDERVALID
        implements Equals, HashCode, ToString
    {

        @XmlValue
        protected BigInteger value;
        @XmlAttribute(name = "TYPE", required = true)
        @XmlSchemaType(name = "anySimpleType")
        protected String type;

        /**
         * Format 999
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setValue(BigInteger value) {
            this.value = value;
        }

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTYPE() {
            if (type == null) {
                return "MONTH";
            } else {
                return type;
            }
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTYPE(String value) {
            this.type = value;
        }

        public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
            if (!(object instanceof ProcedureF05 .DURATIONTENDERVALID)) {
                return false;
            }
            if (this == object) {
                return true;
            }
            final ProcedureF05 .DURATIONTENDERVALID that = ((ProcedureF05 .DURATIONTENDERVALID) object);
            {
                BigInteger lhsValue;
                lhsValue = this.getValue();
                BigInteger rhsValue;
                rhsValue = that.getValue();
                if (!strategy.equals(LocatorUtils.property(thisLocator, "value", lhsValue), LocatorUtils.property(thatLocator, "value", rhsValue), lhsValue, rhsValue)) {
                    return false;
                }
            }
            {
                String lhsTYPE;
                lhsTYPE = this.getTYPE();
                String rhsTYPE;
                rhsTYPE = that.getTYPE();
                if (!strategy.equals(LocatorUtils.property(thisLocator, "type", lhsTYPE), LocatorUtils.property(thatLocator, "type", rhsTYPE), lhsTYPE, rhsTYPE)) {
                    return false;
                }
            }
            return true;
        }

        public boolean equals(Object object) {
            final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
            return equals(null, null, object, strategy);
        }

        public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
            int currentHashCode = 1;
            {
                BigInteger theValue;
                theValue = this.getValue();
                currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "value", theValue), currentHashCode, theValue);
            }
            {
                String theTYPE;
                theTYPE = this.getTYPE();
                currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "type", theTYPE), currentHashCode, theTYPE);
            }
            return currentHashCode;
        }

        public int hashCode() {
            final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
            return this.hashCode(null, strategy);
        }

        public String toString() {
            final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
            final StringBuilder buffer = new StringBuilder();
            append(null, buffer, strategy);
            return buffer.toString();
        }

        public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
            strategy.appendStart(locator, this, buffer);
            appendFields(locator, buffer, strategy);
            strategy.appendEnd(locator, this, buffer);
            return buffer;
        }

        public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
            {
                BigInteger theValue;
                theValue = this.getValue();
                strategy.appendField(locator, this, "value", buffer, theValue);
            }
            {
                String theTYPE;
                theTYPE = this.getTYPE();
                strategy.appendField(locator, this, "type", buffer, theTYPE);
            }
            return buffer;
        }

    }

}
