//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.04 at 01:40:50 PM MEZ 
//


package eu.europa.publications.formex.ted.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * Section IV: PROCEDURE
 * 
 * <p>Java class for procedure_f24 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="procedure_f24">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice minOccurs="0">
 *           &lt;element name="CONTRACT_COVERED_GPA" type="{http://formex.publications.europa.eu/ted/schema/reception/R2.0.9.S01}works"/>
 *           &lt;element name="NO_CONTRACT_COVERED_GPA" type="{http://formex.publications.europa.eu/ted/schema/reception/R2.0.9.S01}works"/>
 *         &lt;/choice>
 *         &lt;group ref="{http://formex.publications.europa.eu/ted/schema/reception/R2.0.9.S01}receipt_tenders"/>
 *         &lt;element ref="{http://formex.publications.europa.eu/ted/schema/reception/R2.0.9.S01}LANGUAGES"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "procedure_f24", propOrder = {
    "nocontractcoveredgpa",
    "contractcoveredgpa",
    "datereceipttenders",
    "timereceipttenders",
    "languages"
})
public class ProcedureF24
    implements Equals, HashCode, ToString
{

    @XmlElement(name = "NO_CONTRACT_COVERED_GPA")
    protected Works nocontractcoveredgpa;
    @XmlElement(name = "CONTRACT_COVERED_GPA")
    protected Works contractcoveredgpa;
    @XmlElement(name = "DATE_RECEIPT_TENDERS", required = true)
    protected XMLGregorianCalendar datereceipttenders;
    @XmlElement(name = "TIME_RECEIPT_TENDERS")
    protected String timereceipttenders;
    @XmlElement(name = "LANGUAGES", required = true)
    protected LANGUAGES languages;

    /**
     * Gets the value of the nocontractcoveredgpa property.
     * 
     * @return
     *     possible object is
     *     {@link Works }
     *     
     */
    public Works getNOCONTRACTCOVEREDGPA() {
        return nocontractcoveredgpa;
    }

    /**
     * Sets the value of the nocontractcoveredgpa property.
     * 
     * @param value
     *     allowed object is
     *     {@link Works }
     *     
     */
    public void setNOCONTRACTCOVEREDGPA(Works value) {
        this.nocontractcoveredgpa = value;
    }

    /**
     * Gets the value of the contractcoveredgpa property.
     * 
     * @return
     *     possible object is
     *     {@link Works }
     *     
     */
    public Works getCONTRACTCOVEREDGPA() {
        return contractcoveredgpa;
    }

    /**
     * Sets the value of the contractcoveredgpa property.
     * 
     * @param value
     *     allowed object is
     *     {@link Works }
     *     
     */
    public void setCONTRACTCOVEREDGPA(Works value) {
        this.contractcoveredgpa = value;
    }

    /**
     * Gets the value of the datereceipttenders property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDATERECEIPTTENDERS() {
        return datereceipttenders;
    }

    /**
     * Sets the value of the datereceipttenders property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDATERECEIPTTENDERS(XMLGregorianCalendar value) {
        this.datereceipttenders = value;
    }

    /**
     * Gets the value of the timereceipttenders property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTIMERECEIPTTENDERS() {
        return timereceipttenders;
    }

    /**
     * Sets the value of the timereceipttenders property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTIMERECEIPTTENDERS(String value) {
        this.timereceipttenders = value;
    }

    /**
     * Gets the value of the languages property.
     * 
     * @return
     *     possible object is
     *     {@link LANGUAGES }
     *     
     */
    public LANGUAGES getLANGUAGES() {
        return languages;
    }

    /**
     * Sets the value of the languages property.
     * 
     * @param value
     *     allowed object is
     *     {@link LANGUAGES }
     *     
     */
    public void setLANGUAGES(LANGUAGES value) {
        this.languages = value;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof ProcedureF24)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final ProcedureF24 that = ((ProcedureF24) object);
        {
            Works lhsNOCONTRACTCOVEREDGPA;
            lhsNOCONTRACTCOVEREDGPA = this.getNOCONTRACTCOVEREDGPA();
            Works rhsNOCONTRACTCOVEREDGPA;
            rhsNOCONTRACTCOVEREDGPA = that.getNOCONTRACTCOVEREDGPA();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "nocontractcoveredgpa", lhsNOCONTRACTCOVEREDGPA), LocatorUtils.property(thatLocator, "nocontractcoveredgpa", rhsNOCONTRACTCOVEREDGPA), lhsNOCONTRACTCOVEREDGPA, rhsNOCONTRACTCOVEREDGPA)) {
                return false;
            }
        }
        {
            Works lhsCONTRACTCOVEREDGPA;
            lhsCONTRACTCOVEREDGPA = this.getCONTRACTCOVEREDGPA();
            Works rhsCONTRACTCOVEREDGPA;
            rhsCONTRACTCOVEREDGPA = that.getCONTRACTCOVEREDGPA();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "contractcoveredgpa", lhsCONTRACTCOVEREDGPA), LocatorUtils.property(thatLocator, "contractcoveredgpa", rhsCONTRACTCOVEREDGPA), lhsCONTRACTCOVEREDGPA, rhsCONTRACTCOVEREDGPA)) {
                return false;
            }
        }
        {
            XMLGregorianCalendar lhsDATERECEIPTTENDERS;
            lhsDATERECEIPTTENDERS = this.getDATERECEIPTTENDERS();
            XMLGregorianCalendar rhsDATERECEIPTTENDERS;
            rhsDATERECEIPTTENDERS = that.getDATERECEIPTTENDERS();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "datereceipttenders", lhsDATERECEIPTTENDERS), LocatorUtils.property(thatLocator, "datereceipttenders", rhsDATERECEIPTTENDERS), lhsDATERECEIPTTENDERS, rhsDATERECEIPTTENDERS)) {
                return false;
            }
        }
        {
            String lhsTIMERECEIPTTENDERS;
            lhsTIMERECEIPTTENDERS = this.getTIMERECEIPTTENDERS();
            String rhsTIMERECEIPTTENDERS;
            rhsTIMERECEIPTTENDERS = that.getTIMERECEIPTTENDERS();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "timereceipttenders", lhsTIMERECEIPTTENDERS), LocatorUtils.property(thatLocator, "timereceipttenders", rhsTIMERECEIPTTENDERS), lhsTIMERECEIPTTENDERS, rhsTIMERECEIPTTENDERS)) {
                return false;
            }
        }
        {
            LANGUAGES lhsLANGUAGES;
            lhsLANGUAGES = this.getLANGUAGES();
            LANGUAGES rhsLANGUAGES;
            rhsLANGUAGES = that.getLANGUAGES();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "languages", lhsLANGUAGES), LocatorUtils.property(thatLocator, "languages", rhsLANGUAGES), lhsLANGUAGES, rhsLANGUAGES)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = 1;
        {
            Works theNOCONTRACTCOVEREDGPA;
            theNOCONTRACTCOVEREDGPA = this.getNOCONTRACTCOVEREDGPA();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "nocontractcoveredgpa", theNOCONTRACTCOVEREDGPA), currentHashCode, theNOCONTRACTCOVEREDGPA);
        }
        {
            Works theCONTRACTCOVEREDGPA;
            theCONTRACTCOVEREDGPA = this.getCONTRACTCOVEREDGPA();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "contractcoveredgpa", theCONTRACTCOVEREDGPA), currentHashCode, theCONTRACTCOVEREDGPA);
        }
        {
            XMLGregorianCalendar theDATERECEIPTTENDERS;
            theDATERECEIPTTENDERS = this.getDATERECEIPTTENDERS();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "datereceipttenders", theDATERECEIPTTENDERS), currentHashCode, theDATERECEIPTTENDERS);
        }
        {
            String theTIMERECEIPTTENDERS;
            theTIMERECEIPTTENDERS = this.getTIMERECEIPTTENDERS();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "timereceipttenders", theTIMERECEIPTTENDERS), currentHashCode, theTIMERECEIPTTENDERS);
        }
        {
            LANGUAGES theLANGUAGES;
            theLANGUAGES = this.getLANGUAGES();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "languages", theLANGUAGES), currentHashCode, theLANGUAGES);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        {
            Works theNOCONTRACTCOVEREDGPA;
            theNOCONTRACTCOVEREDGPA = this.getNOCONTRACTCOVEREDGPA();
            strategy.appendField(locator, this, "nocontractcoveredgpa", buffer, theNOCONTRACTCOVEREDGPA);
        }
        {
            Works theCONTRACTCOVEREDGPA;
            theCONTRACTCOVEREDGPA = this.getCONTRACTCOVEREDGPA();
            strategy.appendField(locator, this, "contractcoveredgpa", buffer, theCONTRACTCOVEREDGPA);
        }
        {
            XMLGregorianCalendar theDATERECEIPTTENDERS;
            theDATERECEIPTTENDERS = this.getDATERECEIPTTENDERS();
            strategy.appendField(locator, this, "datereceipttenders", buffer, theDATERECEIPTTENDERS);
        }
        {
            String theTIMERECEIPTTENDERS;
            theTIMERECEIPTTENDERS = this.getTIMERECEIPTTENDERS();
            strategy.appendField(locator, this, "timereceipttenders", buffer, theTIMERECEIPTTENDERS);
        }
        {
            LANGUAGES theLANGUAGES;
            theLANGUAGES = this.getLANGUAGES();
            strategy.appendField(locator, this, "languages", buffer, theLANGUAGES);
        }
        return buffer;
    }

}
