//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.04 at 01:40:50 PM MEZ 
//


package eu.europa.publications.formex.ted.schema;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for val_range complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="val_range">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="LOW" type="{http://formex.publications.europa.eu/ted/schema/reception/R2.0.9.S01}cost"/>
 *         &lt;element name="HIGH" type="{http://formex.publications.europa.eu/ted/schema/reception/R2.0.9.S01}cost"/>
 *       &lt;/sequence>
 *       &lt;attribute name="CURRENCY" use="required" type="{http://formex.publications.europa.eu/ted/schema/reception/R2.0.9.S01}currencies" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "val_range", propOrder = {
    "low",
    "high"
})
@XmlSeeAlso({
    eu.europa.publications.formex.ted.schema.ObjectContractF06 .VALRANGETOTAL.class
})
public class ValRange
    implements Equals, HashCode, ToString
{

    @XmlElement(name = "LOW", required = true)
    protected BigDecimal low;
    @XmlElement(name = "HIGH", required = true)
    protected BigDecimal high;
    @XmlAttribute(name = "CURRENCY", required = true)
    protected Currencies currency;

    /**
     * Gets the value of the low property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLOW() {
        return low;
    }

    /**
     * Sets the value of the low property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLOW(BigDecimal value) {
        this.low = value;
    }

    /**
     * Gets the value of the high property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getHIGH() {
        return high;
    }

    /**
     * Sets the value of the high property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setHIGH(BigDecimal value) {
        this.high = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return
     *     possible object is
     *     {@link Currencies }
     *     
     */
    public Currencies getCURRENCY() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *     allowed object is
     *     {@link Currencies }
     *     
     */
    public void setCURRENCY(Currencies value) {
        this.currency = value;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof ValRange)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final ValRange that = ((ValRange) object);
        {
            BigDecimal lhsLOW;
            lhsLOW = this.getLOW();
            BigDecimal rhsLOW;
            rhsLOW = that.getLOW();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "low", lhsLOW), LocatorUtils.property(thatLocator, "low", rhsLOW), lhsLOW, rhsLOW)) {
                return false;
            }
        }
        {
            BigDecimal lhsHIGH;
            lhsHIGH = this.getHIGH();
            BigDecimal rhsHIGH;
            rhsHIGH = that.getHIGH();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "high", lhsHIGH), LocatorUtils.property(thatLocator, "high", rhsHIGH), lhsHIGH, rhsHIGH)) {
                return false;
            }
        }
        {
            Currencies lhsCURRENCY;
            lhsCURRENCY = this.getCURRENCY();
            Currencies rhsCURRENCY;
            rhsCURRENCY = that.getCURRENCY();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "currency", lhsCURRENCY), LocatorUtils.property(thatLocator, "currency", rhsCURRENCY), lhsCURRENCY, rhsCURRENCY)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = 1;
        {
            BigDecimal theLOW;
            theLOW = this.getLOW();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "low", theLOW), currentHashCode, theLOW);
        }
        {
            BigDecimal theHIGH;
            theHIGH = this.getHIGH();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "high", theHIGH), currentHashCode, theHIGH);
        }
        {
            Currencies theCURRENCY;
            theCURRENCY = this.getCURRENCY();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "currency", theCURRENCY), currentHashCode, theCURRENCY);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        {
            BigDecimal theLOW;
            theLOW = this.getLOW();
            strategy.appendField(locator, this, "low", buffer, theLOW);
        }
        {
            BigDecimal theHIGH;
            theHIGH = this.getHIGH();
            strategy.appendField(locator, this, "high", buffer, theHIGH);
        }
        {
            Currencies theCURRENCY;
            theCURRENCY = this.getCURRENCY();
            strategy.appendField(locator, this, "currency", buffer, theCURRENCY);
        }
        return buffer;
    }

}
